// Dashboard icon set: the same 1-bit pixel sprites the onboarding wizard uses
// (PixelIcons.tsx, generated by scripts/gen-pixel-icons.py), wrapped in the
// Icon* names the shell and cards import. Every icon is one family, drawn in
// currentColor so a `text-*` class decides its colour, and sized on the 16px
// sprite grid — a sprite scaled to 13px or 28px would have uneven pixels, so
// sizes snap to the nearest grid step instead.
import {
  PixelIconAlert,
  PixelIconArrowRight,
  PixelIconBars,
  PixelIconBell,
  PixelIconBook,
  PixelIconChat,
  PixelIconCheck,
  PixelIconChevronRight,
  PixelIconClock,
  PixelIconDoc,
  PixelIconExit,
  PixelIconGauge,
  PixelIconGear,
  PixelIconGaps,
  PixelIconGrid,
  PixelIconHand,
  PixelIconHome,
  PixelIconHourglass,
  PixelIconInfo,
  PixelIconKey,
  PixelIconLog,
  PixelIconMacro,
  PixelIconMoon,
  PixelIconPeople,
  PixelIconPlus,
  PixelIconRadar,
  PixelIconSearch,
  PixelIconSiren,
  PixelIconSparkle,
  PixelIconSun,
  PixelIconUsers,
} from "./PixelIcons";

type IconProps = { size?: number; className?: string };

/** Snap a caller's size to the 16px sprite grid: 16 up to 24px, 32 to 40, else 48. */
function snap(size: number): number {
  if (size <= 24) return 16;
  if (size <= 40) return 32;
  return 48;
}

export function IconHome({ size = 16, className }: IconProps) {
  return <PixelIconHome size={snap(size)} className={className} />;
}

export function IconGrid({ size = 16, className }: IconProps) {
  return <PixelIconGrid size={snap(size)} className={className} />;
}

export function IconKey({ size = 16, className }: IconProps) {
  return <PixelIconKey size={snap(size)} className={className} />;
}

export function IconChat({ size = 16, className }: IconProps) {
  return <PixelIconChat size={snap(size)} className={className} />;
}

export function IconDoc({ size = 16, className }: IconProps) {
  return <PixelIconDoc size={snap(size)} className={className} />;
}

export function IconGaps({ size = 16, className }: IconProps) {
  return <PixelIconGaps size={snap(size)} className={className} />;
}

export function IconUsers({ size = 16, className }: IconProps) {
  return <PixelIconUsers size={snap(size)} className={className} />;
}

export function IconPeople({ size = 16, className }: IconProps) {
  return <PixelIconPeople size={snap(size)} className={className} />;
}

export function IconMacro({ size = 16, className }: IconProps) {
  return <PixelIconMacro size={snap(size)} className={className} />;
}

export function IconBars({ size = 16, className }: IconProps) {
  return <PixelIconBars size={snap(size)} className={className} />;
}

export function IconGauge({ size = 16, className }: IconProps) {
  return <PixelIconGauge size={snap(size)} className={className} />;
}

export function IconRadar({ size = 16, className }: IconProps) {
  return <PixelIconRadar size={snap(size)} className={className} />;
}

export function IconAlert({ size = 16, className }: IconProps) {
  return <PixelIconAlert size={snap(size)} className={className} />;
}

export function IconSiren({ size = 16, className }: IconProps) {
  return <PixelIconSiren size={snap(size)} className={className} />;
}

export function IconLog({ size = 16, className }: IconProps) {
  return <PixelIconLog size={snap(size)} className={className} />;
}

export function IconClock({ size = 16, className }: IconProps) {
  return <PixelIconClock size={snap(size)} className={className} />;
}

export function IconHourglass({ size = 16, className }: IconProps) {
  return <PixelIconHourglass size={snap(size)} className={className} />;
}

export function IconGear({ size = 16, className }: IconProps) {
  return <PixelIconGear size={snap(size)} className={className} />;
}

export function IconSearch({ size = 16, className }: IconProps) {
  return <PixelIconSearch size={snap(size)} className={className} />;
}

export function IconBell({ size = 16, className }: IconProps) {
  return <PixelIconBell size={snap(size)} className={className} />;
}

export function IconChevronRight({ size = 16, className }: IconProps) {
  return <PixelIconChevronRight size={snap(size)} className={className} />;
}

export function IconArrowRight({ size = 16, className }: IconProps) {
  return <PixelIconArrowRight size={snap(size)} className={className} />;
}

export function IconCheck({ size = 16, className }: IconProps) {
  return <PixelIconCheck size={snap(size)} className={className} />;
}

export function IconHand({ size = 16, className }: IconProps) {
  return <PixelIconHand size={snap(size)} className={className} />;
}

export function IconMoon({ size = 16, className }: IconProps) {
  return <PixelIconMoon size={snap(size)} className={className} />;
}

export function IconSun({ size = 16, className }: IconProps) {
  return <PixelIconSun size={snap(size)} className={className} />;
}

export function IconBook({ size = 16, className }: IconProps) {
  return <PixelIconBook size={snap(size)} className={className} />;
}

export function IconExit({ size = 16, className }: IconProps) {
  return <PixelIconExit size={snap(size)} className={className} />;
}

export function IconInfo({ size = 16, className }: IconProps) {
  return <PixelIconInfo size={snap(size)} className={className} />;
}

export function IconPlus({ size = 16, className }: IconProps) {
  return <PixelIconPlus size={snap(size)} className={className} />;
}

export function IconSparkle({ size = 16, className }: IconProps) {
  return <PixelIconSparkle size={snap(size)} className={className} />;
}
