// GENERATED by scripts/gen-pixel-icons.py from the "1-bit Pixel Icons" pack —
// edit the mapping there and re-run instead of editing this file. Shared by the
// onboarding wizard (app/wizard/_components/PixelIcons.tsx re-exports it) and
// the dashboard (app/_components/icons.tsx wraps these as Icon*).
// Only each 16x16 sprite's outline pixels are kept, drawn as crisp cells in
// currentColor, so icons take their context's text colour. Render at
// multiples of 16px (16, 32, 48) to keep every pixel square.
type IconProps = { size?: number; className?: string };

function PixelSvg({ size, className, d }: { size: number; className?: string; d: string }) {
  return (
    <svg
      width={size}
      height={size}
      viewBox="0 0 16 16"
      fill="currentColor"
      shapeRendering="crispEdges"
      className={className}
      aria-hidden="true"
      focusable="false"
    >
      <path d={d} />
    </svg>
  );
}

// Sprite outlines — one constant per unique pack sprite, shared by every
// component that draws the same mark.

// Controller_Buttons_Menu_Options_Settings.png
const SPRITE_CONTROLLER_BUTTONS_MENU_OPTIONS_SETTINGS =
  "M3 2h10v1h-10zM2 3h2v1h-2zM12 3h2v1h-2zM1 4h2v1h-2zM5 4h6v1h-6zM13 4h2v1h-2zM1 5h1v1h-1zM14 5h1v1h-1zM1 6h1v1h-1zM5 6h6v1h-6zM14 6h1v1h-1zM1 7h1v1h-1zM14 7h1v1h-1zM1 8h2v1h-2zM5 8h6v1h-6zM13 8h2v1h-2zM1 9h1v1h-1zM3 9h1v1h-1zM12 9h1v1h-1zM14 9h1v1h-1zM1 10h2v1h-2zM4 10h8v1h-8zM13 10h2v1h-2zM2 11h2v1h-2zM12 11h2v1h-2zM3 12h10v1h-10z";

// Software_Speech_Bubble_Three_Dots_Dialogue.png
const SPRITE_SOFTWARE_SPEECH_BUBBLE_THREE_DOTS_DIALOGUE =
  "M3 2h10v1h-10zM2 3h2v1h-2zM12 3h2v1h-2zM2 4h1v1h-1zM13 4h1v1h-1zM2 5h1v1h-1zM13 5h1v1h-1zM2 6h1v1h-1zM13 6h1v1h-1zM2 7h1v1h-1zM4 7h2v1h-2zM7 7h2v1h-2zM10 7h2v1h-2zM13 7h1v1h-1zM2 8h1v1h-1zM4 8h2v1h-2zM7 8h2v1h-2zM10 8h2v1h-2zM13 8h1v1h-1zM2 9h1v1h-1zM13 9h1v1h-1zM2 10h2v1h-2zM12 10h2v1h-2zM3 11h2v1h-2zM8 11h5v1h-5zM3 12h1v1h-1zM7 12h2v1h-2zM3 13h5v1h-5z";

// Software_File_Document_Page_Text_Word.png
const SPRITE_SOFTWARE_FILE_DOCUMENT_PAGE_TEXT_WORD =
  "M2 1h8v1h-8zM2 2h1v1h-1zM9 2h2v1h-2zM2 3h1v1h-1zM4 3h4v1h-4zM10 3h2v1h-2zM2 4h1v1h-1zM4 4h1v1h-1zM7 4h1v1h-1zM11 4h2v1h-2zM2 5h1v1h-1zM4 5h1v1h-1zM7 5h1v1h-1zM12 5h1v1h-1zM2 6h1v1h-1zM4 6h7v1h-7zM12 6h1v1h-1zM2 7h1v1h-1zM4 7h1v1h-1zM10 7h1v1h-1zM12 7h1v1h-1zM2 8h1v1h-1zM4 8h7v1h-7zM12 8h1v1h-1zM2 9h1v1h-1zM4 9h1v1h-1zM10 9h1v1h-1zM12 9h1v1h-1zM2 10h1v1h-1zM4 10h7v1h-7zM12 10h1v1h-1zM2 11h1v1h-1zM4 11h1v1h-1zM9 11h2v1h-2zM12 11h1v1h-1zM2 12h1v1h-1zM4 12h7v1h-7zM12 12h1v1h-1zM2 13h1v1h-1zM12 13h1v1h-1zM2 14h11v1h-11z";

// Travel_Person_Player_Character_Three_People_Multiplayer.png
const SPRITE_TRAVEL_PERSON_PLAYER_CHARACTER_THREE_PEOPLE_MULTIPLAYER =
  "M5 1h5v1h-5zM1 2h5v1h-5zM9 2h5v1h-5zM0 3h2v1h-2zM4 3h1v1h-1zM10 3h1v1h-1zM13 3h2v1h-2zM0 4h1v1h-1zM4 4h1v1h-1zM10 4h1v1h-1zM14 4h1v1h-1zM0 5h1v1h-1zM4 5h1v1h-1zM10 5h1v1h-1zM14 5h1v1h-1zM0 6h2v1h-2zM4 6h2v1h-2zM9 6h2v1h-2zM13 6h2v1h-2zM1 7h13v1h-13zM0 8h2v1h-2zM5 8h1v1h-1zM9 8h1v1h-1zM13 8h2v1h-2zM0 9h1v1h-1zM4 9h1v1h-1zM10 9h1v1h-1zM14 9h1v1h-1zM0 10h1v1h-1zM3 10h1v1h-1zM11 10h1v1h-1zM14 10h1v1h-1zM0 11h1v1h-1zM3 11h1v1h-1zM11 11h1v1h-1zM14 11h1v1h-1zM0 12h4v1h-4zM11 12h4v1h-4zM3 13h9v1h-9z";

// Software_Email_Message_Send_Paper_Plane.png
const SPRITE_SOFTWARE_EMAIL_MESSAGE_SEND_PAPER_PLANE =
  "M11 1h4v1h-4zM9 2h3v1h-3zM14 2h1v1h-1zM7 3h3v1h-3zM14 3h1v1h-1zM5 4h3v1h-3zM11 4h1v1h-1zM13 4h2v1h-2zM3 5h3v1h-3zM9 5h2v1h-2zM13 5h1v1h-1zM1 6h3v1h-3zM8 6h2v1h-2zM12 6h2v1h-2zM1 7h1v1h-1zM7 7h2v1h-2zM12 7h1v1h-1zM1 8h3v1h-3zM6 8h2v1h-2zM11 8h2v1h-2zM3 9h2v1h-2zM6 9h1v1h-1zM11 9h1v1h-1zM4 10h1v1h-1zM6 10h2v1h-2zM10 10h2v1h-2zM4 11h1v1h-1zM7 11h2v1h-2zM10 11h1v1h-1zM4 12h1v1h-1zM6 12h5v1h-5zM4 13h3v1h-3z";

// Software_Notepad_Wordpad_Text_Editor.png
const SPRITE_SOFTWARE_NOTEPAD_WORDPAD_TEXT_EDITOR =
  "M2 0h11v1h-11zM2 1h1v1h-1zM4 1h1v1h-1zM6 1h1v1h-1zM8 1h1v1h-1zM10 1h1v1h-1zM12 1h1v1h-1zM2 2h1v1h-1zM4 2h1v1h-1zM6 2h1v1h-1zM8 2h1v1h-1zM10 2h1v1h-1zM12 2h1v1h-1zM2 3h2v1h-2zM5 3h1v1h-1zM7 3h1v1h-1zM9 3h1v1h-1zM11 3h2v1h-2zM2 4h1v1h-1zM12 4h1v1h-1zM2 5h1v1h-1zM12 5h1v1h-1zM2 6h1v1h-1zM4 6h7v1h-7zM12 6h1v1h-1zM2 7h1v1h-1zM12 7h1v1h-1zM2 8h1v1h-1zM4 8h7v1h-7zM12 8h1v1h-1zM2 9h1v1h-1zM12 9h1v1h-1zM2 10h1v1h-1zM4 10h7v1h-7zM12 10h1v1h-1zM2 11h1v1h-1zM12 11h1v1h-1zM2 12h1v1h-1zM4 12h4v1h-4zM12 12h1v1h-1zM2 13h1v1h-1zM12 13h1v1h-1zM2 14h11v1h-11z";

// Platforms_GitHub.png
const SPRITE_PLATFORMS_GITHUB =
  "M4 1h8v1h-8zM3 2h2v1h-2zM11 2h2v1h-2zM2 3h2v1h-2zM5 3h1v1h-1zM10 3h1v1h-1zM12 3h2v1h-2zM1 4h2v1h-2zM5 4h2v1h-2zM9 4h2v1h-2zM13 4h2v1h-2zM1 5h1v1h-1zM5 5h6v1h-6zM14 5h1v1h-1zM1 6h1v1h-1zM4 6h8v1h-8zM14 6h1v1h-1zM1 7h1v1h-1zM4 7h8v1h-8zM14 7h1v1h-1zM1 8h1v1h-1zM4 8h8v1h-8zM14 8h1v1h-1zM1 9h1v1h-1zM5 9h6v1h-6zM14 9h1v1h-1zM1 10h1v1h-1zM7 10h2v1h-2zM14 10h1v1h-1zM1 11h2v1h-2zM4 11h1v1h-1zM6 11h4v1h-4zM13 11h2v1h-2zM2 12h2v1h-2zM5 12h5v1h-5zM12 12h2v1h-2zM3 13h2v1h-2zM6 13h4v1h-4zM11 13h2v1h-2zM4 14h8v1h-8z";

// Software_Internet_Upload_from_Disk.png
const SPRITE_SOFTWARE_INTERNET_UPLOAD_FROM_DISK =
  "M6 1h3v1h-3zM5 2h2v1h-2zM8 2h2v1h-2zM4 3h2v1h-2zM9 3h2v1h-2zM3 4h2v1h-2zM10 4h2v1h-2zM3 5h1v1h-1zM11 5h1v1h-1zM3 6h3v1h-3zM9 6h3v1h-3zM1 7h5v1h-5zM9 7h5v1h-5zM1 8h1v1h-1zM5 8h1v1h-1zM9 8h1v1h-1zM13 8h1v1h-1zM1 9h1v1h-1zM3 9h3v1h-3zM9 9h3v1h-3zM13 9h1v1h-1zM1 10h1v1h-1zM3 10h1v1h-1zM5 10h1v1h-1zM9 10h1v1h-1zM11 10h1v1h-1zM13 10h1v1h-1zM1 11h1v1h-1zM3 11h9v1h-9zM13 11h1v1h-1zM1 12h1v1h-1zM13 12h1v1h-1zM1 13h1v1h-1zM13 13h1v1h-1zM1 14h13v1h-13z";

// Software_File_Document_Page_Plus_Add_New.png
const SPRITE_SOFTWARE_FILE_DOCUMENT_PAGE_PLUS_ADD_NEW =
  "M2 1h8v1h-8zM2 2h1v1h-1zM9 2h2v1h-2zM2 3h1v1h-1zM4 3h4v1h-4zM10 3h2v1h-2zM2 4h1v1h-1zM4 4h1v1h-1zM7 4h1v1h-1zM11 4h2v1h-2zM2 5h1v1h-1zM4 5h1v1h-1zM7 5h1v1h-1zM12 5h1v1h-1zM2 6h1v1h-1zM4 6h1v1h-1zM6 6h5v1h-5zM12 6h1v1h-1zM2 7h1v1h-1zM4 7h1v1h-1zM6 7h1v1h-1zM8 7h1v1h-1zM10 7h1v1h-1zM12 7h1v1h-1zM2 8h1v1h-1zM4 8h3v1h-3zM8 8h3v1h-3zM12 8h1v1h-1zM2 9h1v1h-1zM4 9h1v1h-1zM10 9h1v1h-1zM12 9h1v1h-1zM2 10h1v1h-1zM4 10h3v1h-3zM8 10h3v1h-3zM12 10h1v1h-1zM2 11h1v1h-1zM4 11h1v1h-1zM6 11h1v1h-1zM8 11h1v1h-1zM10 11h1v1h-1zM12 11h1v1h-1zM2 12h1v1h-1zM4 12h7v1h-7zM12 12h1v1h-1zM2 13h1v1h-1zM12 13h1v1h-1zM2 14h11v1h-11z";

// Software_Storage_Drives_Discs_Disks_Server_1.png
const SPRITE_SOFTWARE_STORAGE_DRIVES_DISCS_DISKS_SERVER_1 =
  "M4 1h7v1h-7zM2 2h3v1h-3zM10 2h3v1h-3zM1 3h2v1h-2zM12 3h2v1h-2zM1 4h1v1h-1zM13 4h1v1h-1zM1 5h2v1h-2zM12 5h2v1h-2zM1 6h1v1h-1zM3 6h2v1h-2zM10 6h2v1h-2zM13 6h1v1h-1zM1 7h1v1h-1zM5 7h5v1h-5zM13 7h1v1h-1zM1 8h2v1h-2zM12 8h2v1h-2zM1 9h1v1h-1zM3 9h2v1h-2zM10 9h2v1h-2zM13 9h1v1h-1zM1 10h1v1h-1zM5 10h5v1h-5zM13 10h1v1h-1zM1 11h2v1h-2zM12 11h2v1h-2zM2 12h3v1h-3zM10 12h3v1h-3zM4 13h7v1h-7z";

// Software_Hardware_Monitor_Display_PC_Computer.png
const SPRITE_SOFTWARE_HARDWARE_MONITOR_DISPLAY_PC_COMPUTER =
  "M1 2h14v1h-14zM1 3h1v1h-1zM14 3h1v1h-1zM1 4h1v1h-1zM14 4h1v1h-1zM1 5h1v1h-1zM4 5h8v1h-8zM14 5h1v1h-1zM1 6h1v1h-1zM4 6h1v1h-1zM11 6h1v1h-1zM14 6h1v1h-1zM1 7h1v1h-1zM4 7h1v1h-1zM11 7h1v1h-1zM14 7h1v1h-1zM1 8h1v1h-1zM4 8h8v1h-8zM14 8h1v1h-1zM1 9h1v1h-1zM14 9h1v1h-1zM1 10h1v1h-1zM14 10h1v1h-1zM1 11h6v1h-6zM9 11h6v1h-6zM3 12h2v1h-2zM11 12h2v1h-2zM3 13h1v1h-1zM12 13h1v1h-1zM3 14h10v1h-10z";

// RPG_Magic_Sparkles_Enchantment.png
const SPRITE_RPG_MAGIC_SPARKLES_ENCHANTMENT =
  "M2 1h3v1h-3zM6 1h3v1h-3zM11 1h3v1h-3zM2 2h1v1h-1zM4 2h1v1h-1zM6 2h1v1h-1zM8 2h1v1h-1zM10 2h2v1h-2zM13 2h2v1h-2zM2 3h5v1h-5zM8 3h3v1h-3zM14 3h1v1h-1zM5 4h1v1h-1zM9 4h3v1h-3zM13 4h2v1h-2zM3 5h3v1h-3zM9 5h5v1h-5zM1 6h3v1h-3zM7 6h1v1h-1zM11 6h3v1h-3zM1 7h1v1h-1zM6 7h3v1h-3zM13 7h1v1h-1zM1 8h3v1h-3zM7 8h1v1h-1zM11 8h3v1h-3zM3 9h3v1h-3zM9 9h6v1h-6zM2 10h4v1h-4zM9 10h1v1h-1zM12 10h1v1h-1zM14 10h1v1h-1zM1 11h2v1h-2zM4 11h3v1h-3zM8 11h2v1h-2zM12 11h3v1h-3zM1 12h1v1h-1zM5 12h2v1h-2zM8 12h4v1h-4zM1 13h2v1h-2zM4 13h6v1h-6zM11 13h1v1h-1zM2 14h3v1h-3zM9 14h3v1h-3z";

// Software_Checkbox_Checkmarked_Yes_Done_Todo.png
const SPRITE_SOFTWARE_CHECKBOX_CHECKMARKED_YES_DONE_TODO =
  "M1 1h14v1h-14zM1 2h1v1h-1zM10 2h3v1h-3zM14 2h1v1h-1zM1 3h1v1h-1zM3 3h8v1h-8zM13 3h2v1h-2zM1 4h1v1h-1zM3 4h4v1h-4zM8 4h2v1h-2zM12 4h2v1h-2zM1 5h1v1h-1zM3 5h1v1h-1zM6 5h3v1h-3zM11 5h3v1h-3zM1 6h1v1h-1zM3 6h2v1h-2zM7 6h1v1h-1zM10 6h2v1h-2zM13 6h1v1h-1zM1 7h1v1h-1zM3 7h3v1h-3zM10 7h2v1h-2zM13 7h1v1h-1zM1 8h1v1h-1zM3 8h1v1h-1zM5 8h1v1h-1zM9 8h3v1h-3zM13 8h1v1h-1zM1 9h1v1h-1zM3 9h1v1h-1zM5 9h2v1h-2zM9 9h1v1h-1zM11 9h1v1h-1zM13 9h1v1h-1zM1 10h1v1h-1zM3 10h1v1h-1zM6 10h1v1h-1zM8 10h2v1h-2zM11 10h1v1h-1zM13 10h1v1h-1zM1 11h1v1h-1zM3 11h9v1h-9zM13 11h1v1h-1zM1 12h1v1h-1zM13 12h1v1h-1zM1 13h13v1h-13z";

// Software_Warning_Sign_Triangle_Exclaimation_Mark_Error.png
const SPRITE_SOFTWARE_WARNING_SIGN_TRIANGLE_EXCLAIMATION_MARK_ERROR =
  "M6 1h3v1h-3zM5 2h2v1h-2zM8 2h2v1h-2zM5 3h1v1h-1zM9 3h1v1h-1zM4 4h2v1h-2zM9 4h2v1h-2zM4 5h1v1h-1zM6 5h3v1h-3zM10 5h1v1h-1zM3 6h2v1h-2zM6 6h1v1h-1zM8 6h1v1h-1zM10 6h2v1h-2zM3 7h1v1h-1zM6 7h1v1h-1zM8 7h1v1h-1zM11 7h1v1h-1zM2 8h2v1h-2zM6 8h1v1h-1zM8 8h1v1h-1zM11 8h2v1h-2zM2 9h1v1h-1zM6 9h3v1h-3zM12 9h1v1h-1zM1 10h2v1h-2zM12 10h2v1h-2zM1 11h1v1h-1zM6 11h3v1h-3zM13 11h1v1h-1zM1 12h1v1h-1zM13 12h1v1h-1zM1 13h13v1h-13z";

// Software_Clock_Time_Wait_2.png
const SPRITE_SOFTWARE_CLOCK_TIME_WAIT_2 =
  "M4 3h7v1h-7zM3 4h2v1h-2zM10 4h2v1h-2zM2 5h2v1h-2zM5 5h5v1h-5zM11 5h2v1h-2zM2 6h1v1h-1zM4 6h2v1h-2zM7 6h1v1h-1zM9 6h2v1h-2zM12 6h1v1h-1zM2 7h1v1h-1zM4 7h1v1h-1zM7 7h1v1h-1zM10 7h1v1h-1zM12 7h1v1h-1zM2 8h1v1h-1zM4 8h1v1h-1zM7 8h2v1h-2zM10 8h1v1h-1zM12 8h1v1h-1zM2 9h1v1h-1zM4 9h1v1h-1zM10 9h1v1h-1zM12 9h1v1h-1zM2 10h1v1h-1zM4 10h2v1h-2zM9 10h2v1h-2zM12 10h1v1h-1zM2 11h2v1h-2zM5 11h5v1h-5zM11 11h2v1h-2zM3 12h2v1h-2zM10 12h2v1h-2zM4 13h7v1h-7z";

// Software_Warning_Sign_Circle_Information_Help.png
const SPRITE_SOFTWARE_WARNING_SIGN_CIRCLE_INFORMATION_HELP =
  "M4 1h7v1h-7zM3 2h2v1h-2zM10 2h2v1h-2zM2 3h2v1h-2zM6 3h3v1h-3zM11 3h2v1h-2zM1 4h2v1h-2zM6 4h3v1h-3zM12 4h2v1h-2zM1 5h1v1h-1zM13 5h1v1h-1zM1 6h1v1h-1zM5 6h4v1h-4zM13 6h1v1h-1zM1 7h1v1h-1zM6 7h1v1h-1zM8 7h1v1h-1zM13 7h1v1h-1zM1 8h1v1h-1zM6 8h1v1h-1zM8 8h1v1h-1zM13 8h1v1h-1zM1 9h1v1h-1zM6 9h1v1h-1zM8 9h1v1h-1zM13 9h1v1h-1zM1 10h2v1h-2zM6 10h1v1h-1zM8 10h1v1h-1zM12 10h2v1h-2zM2 11h2v1h-2zM5 11h5v1h-5zM11 11h2v1h-2zM3 12h2v1h-2zM10 12h2v1h-2zM4 13h7v1h-7z";

// Tools_Crafting_Padlock_Locked.png
const SPRITE_TOOLS_CRAFTING_PADLOCK_LOCKED =
  "M4 2h7v1h-7zM3 3h2v1h-2zM10 3h2v1h-2zM3 4h1v1h-1zM11 4h1v1h-1zM3 5h1v1h-1zM6 5h3v1h-3zM11 5h1v1h-1zM3 6h1v1h-1zM6 6h1v1h-1zM8 6h1v1h-1zM11 6h1v1h-1zM2 7h11v1h-11zM2 8h1v1h-1zM12 8h1v1h-1zM2 9h1v1h-1zM6 9h3v1h-3zM12 9h1v1h-1zM2 10h1v1h-1zM6 10h3v1h-3zM12 10h1v1h-1zM2 11h1v1h-1zM7 11h1v1h-1zM12 11h1v1h-1zM2 12h1v1h-1zM7 12h1v1h-1zM12 12h1v1h-1zM2 13h1v1h-1zM12 13h1v1h-1zM2 14h11v1h-11z";

// Software_Clipbaord_List_File_Copy_Paste.png
const SPRITE_SOFTWARE_CLIPBAORD_LIST_FILE_COPY_PASTE =
  "M5 0h6v1h-6zM2 1h4v1h-4zM10 1h4v1h-4zM2 2h1v1h-1zM5 2h6v1h-6zM13 2h1v1h-1zM2 3h1v1h-1zM13 3h1v1h-1zM2 4h1v1h-1zM4 4h8v1h-8zM13 4h1v1h-1zM2 5h1v1h-1zM4 5h1v1h-1zM11 5h1v1h-1zM13 5h1v1h-1zM2 6h1v1h-1zM4 6h8v1h-8zM13 6h1v1h-1zM2 7h1v1h-1zM4 7h1v1h-1zM11 7h1v1h-1zM13 7h1v1h-1zM2 8h1v1h-1zM4 8h8v1h-8zM13 8h1v1h-1zM2 9h1v1h-1zM4 9h1v1h-1zM11 9h1v1h-1zM13 9h1v1h-1zM2 10h1v1h-1zM4 10h8v1h-8zM13 10h1v1h-1zM2 11h1v1h-1zM4 11h1v1h-1zM10 11h2v1h-2zM13 11h1v1h-1zM2 12h1v1h-1zM4 12h8v1h-8zM13 12h1v1h-1zM2 13h1v1h-1zM13 13h1v1h-1zM2 14h12v1h-12z";

// Software_Signs_Maths_Multiplication_X_Crossout_Checkmark_Cancel.png
const SPRITE_SOFTWARE_SIGNS_MATHS_MULTIPLICATION_X_CROSSOUT_CHECKMARK_CANCEL =
  "M2 2h4v1h-4zM9 2h4v1h-4zM2 3h1v1h-1zM5 3h2v1h-2zM8 3h2v1h-2zM12 3h1v1h-1zM2 4h1v1h-1zM6 4h3v1h-3zM12 4h1v1h-1zM2 5h2v1h-2zM7 5h1v1h-1zM11 5h2v1h-2zM3 6h2v1h-2zM10 6h2v1h-2zM4 7h2v1h-2zM9 7h2v1h-2zM3 8h2v1h-2zM10 8h2v1h-2zM2 9h2v1h-2zM7 9h1v1h-1zM11 9h2v1h-2zM2 10h1v1h-1zM6 10h3v1h-3zM12 10h1v1h-1zM2 11h1v1h-1zM5 11h2v1h-2zM8 11h2v1h-2zM12 11h1v1h-1zM2 12h4v1h-4zM9 12h4v1h-4z";

// Arrows_Left_West.png
const SPRITE_ARROWS_LEFT_WEST =
  "M4 3h3v1h-3zM3 4h2v1h-2zM6 4h1v1h-1zM2 5h2v1h-2zM6 5h1v1h-1zM11 5h3v1h-3zM1 6h2v1h-2zM6 6h6v1h-6zM13 6h1v1h-1zM1 7h1v1h-1zM6 7h1v1h-1zM13 7h1v1h-1zM1 8h2v1h-2zM6 8h6v1h-6zM13 8h1v1h-1zM2 9h2v1h-2zM6 9h1v1h-1zM11 9h3v1h-3zM3 10h2v1h-2zM6 10h1v1h-1zM4 11h3v1h-3z";

// Arrows_Right_East.png
const SPRITE_ARROWS_RIGHT_EAST =
  "M9 3h3v1h-3zM9 4h1v1h-1zM11 4h2v1h-2zM2 5h3v1h-3zM9 5h1v1h-1zM12 5h2v1h-2zM2 6h1v1h-1zM4 6h6v1h-6zM13 6h2v1h-2zM2 7h1v1h-1zM9 7h1v1h-1zM14 7h1v1h-1zM2 8h1v1h-1zM4 8h6v1h-6zM13 8h2v1h-2zM2 9h3v1h-3zM9 9h1v1h-1zM12 9h2v1h-2zM9 10h1v1h-1zM11 10h2v1h-2zM9 11h3v1h-3z";

// Map_Markers_Building_Home_House.png
const SPRITE_MAP_MARKERS_BUILDING_HOME_HOUSE =
  "M6 1h7v1h-7zM5 2h2v1h-2zM8 2h2v1h-2zM12 2h1v1h-1zM4 3h2v1h-2zM9 3h1v1h-1zM12 3h1v1h-1zM3 4h2v1h-2zM12 4h1v1h-1zM2 5h2v1h-2zM7 5h1v1h-1zM12 5h1v1h-1zM1 6h2v1h-2zM6 6h3v1h-3zM12 6h2v1h-2zM1 7h1v1h-1zM5 7h2v1h-2zM8 7h2v1h-2zM13 7h1v1h-1zM1 8h1v1h-1zM4 8h2v1h-2zM9 8h2v1h-2zM13 8h1v1h-1zM1 9h4v1h-4zM10 9h4v1h-4zM2 10h1v1h-1zM6 10h3v1h-3zM12 10h1v1h-1zM2 11h1v1h-1zM6 11h1v1h-1zM8 11h1v1h-1zM12 11h1v1h-1zM2 12h1v1h-1zM6 12h1v1h-1zM8 12h1v1h-1zM12 12h1v1h-1zM2 13h1v1h-1zM6 13h1v1h-1zM8 13h1v1h-1zM12 13h1v1h-1zM2 14h5v1h-5zM8 14h5v1h-5z";

// Software_File_Folder_Directory_Explorer.png
const SPRITE_SOFTWARE_FILE_FOLDER_DIRECTORY_EXPLORER =
  "M1 2h7v1h-7zM1 3h1v1h-1zM7 3h7v1h-7zM1 4h1v1h-1zM3 4h4v1h-4zM13 4h2v1h-2zM1 5h1v1h-1zM3 5h1v1h-1zM6 5h7v1h-7zM14 5h1v1h-1zM1 6h1v1h-1zM3 6h5v1h-5zM14 6h1v1h-1zM1 7h1v1h-1zM14 7h1v1h-1zM1 8h1v1h-1zM14 8h1v1h-1zM1 9h1v1h-1zM14 9h1v1h-1zM1 10h1v1h-1zM14 10h1v1h-1zM1 11h1v1h-1zM14 11h1v1h-1zM1 12h1v1h-1zM14 12h1v1h-1zM1 13h14v1h-14z";

// Tools_Crafting_Key_Unlock_1.png
const SPRITE_TOOLS_CRAFTING_KEY_UNLOCK_1 =
  "M3 4h4v1h-4zM2 5h2v1h-2zM6 5h2v1h-2zM1 6h2v1h-2zM7 6h8v1h-8zM1 7h1v1h-1zM4 7h2v1h-2zM14 7h1v1h-1zM1 8h1v1h-1zM4 8h2v1h-2zM14 8h1v1h-1zM1 9h2v1h-2zM7 9h4v1h-4zM14 9h1v1h-1zM2 10h2v1h-2zM6 10h2v1h-2zM10 10h1v1h-1zM12 10h1v1h-1zM14 10h1v1h-1zM3 11h4v1h-4zM10 11h5v1h-5z";

// Software_Speech_Bubble_Question_Mark_Quest_Return_Finished.png
const SPRITE_SOFTWARE_SPEECH_BUBBLE_QUESTION_MARK_QUEST_RETURN_FINISHED =
  "M3 2h10v1h-10zM2 3h2v1h-2zM12 3h2v1h-2zM2 4h1v1h-1zM5 4h5v1h-5zM13 4h1v1h-1zM2 5h1v1h-1zM5 5h2v1h-2zM9 5h2v1h-2zM13 5h1v1h-1zM2 6h1v1h-1zM8 6h3v1h-3zM13 6h1v1h-1zM2 7h1v1h-1zM7 7h3v1h-3zM13 7h1v1h-1zM2 8h1v1h-1zM13 8h1v1h-1zM2 9h1v1h-1zM7 9h2v1h-2zM13 9h1v1h-1zM2 10h2v1h-2zM12 10h2v1h-2zM3 11h2v1h-2zM8 11h5v1h-5zM3 12h1v1h-1zM7 12h2v1h-2zM3 13h5v1h-5z";

// Tools_Crafting_Books_Manual_Documentation_Reading.png
const SPRITE_TOOLS_CRAFTING_BOOKS_MANUAL_DOCUMENTATION_READING =
  "M3 1h10v1h-10zM2 2h2v1h-2zM12 2h1v1h-1zM2 3h1v1h-1zM6 3h4v1h-4zM12 3h1v1h-1zM2 4h1v1h-1zM6 4h4v1h-4zM12 4h1v1h-1zM2 5h1v1h-1zM12 5h1v1h-1zM2 6h1v1h-1zM12 6h1v1h-1zM2 7h1v1h-1zM12 7h1v1h-1zM2 8h1v1h-1zM12 8h1v1h-1zM2 9h1v1h-1zM12 9h1v1h-1zM2 10h1v1h-1zM4 10h9v1h-9zM2 11h1v1h-1zM4 11h1v1h-1zM12 11h1v1h-1zM2 12h1v1h-1zM4 12h9v1h-9zM2 13h2v1h-2zM12 13h1v1h-1zM3 14h10v1h-10z";

// Software_Speech_Bubble_Exclaimation_Mark_Quest_New.png
const SPRITE_SOFTWARE_SPEECH_BUBBLE_EXCLAIMATION_MARK_QUEST_NEW =
  "M3 2h10v1h-10zM2 3h2v1h-2zM12 3h2v1h-2zM2 4h1v1h-1zM7 4h2v1h-2zM13 4h1v1h-1zM2 5h1v1h-1zM7 5h2v1h-2zM13 5h1v1h-1zM2 6h1v1h-1zM7 6h2v1h-2zM13 6h1v1h-1zM2 7h1v1h-1zM7 7h2v1h-2zM13 7h1v1h-1zM2 8h1v1h-1zM13 8h1v1h-1zM2 9h1v1h-1zM7 9h2v1h-2zM13 9h1v1h-1zM2 10h2v1h-2zM12 10h2v1h-2zM3 11h2v1h-2zM8 11h5v1h-5zM3 12h1v1h-1zM7 12h2v1h-2zM3 13h5v1h-5z";

// Travel_Person_People_Two.png
const SPRITE_TRAVEL_PERSON_PEOPLE_TWO =
  "M3 1h4v1h-4zM8 1h4v1h-4zM3 2h1v1h-1zM6 2h1v1h-1zM8 2h1v1h-1zM11 2h1v1h-1zM3 3h1v1h-1zM6 3h1v1h-1zM8 3h1v1h-1zM11 3h1v1h-1zM2 4h11v1h-11zM2 5h1v1h-1zM7 5h1v1h-1zM12 5h1v1h-1zM2 6h1v1h-1zM7 6h1v1h-1zM12 6h1v1h-1zM2 7h1v1h-1zM7 7h1v1h-1zM12 7h1v1h-1zM2 8h1v1h-1zM7 8h1v1h-1zM12 8h1v1h-1zM2 9h2v1h-2zM6 9h3v1h-3zM11 9h2v1h-2zM3 10h1v1h-1zM6 10h1v1h-1zM8 10h1v1h-1zM11 10h1v1h-1zM3 11h1v1h-1zM6 11h1v1h-1zM8 11h1v1h-1zM11 11h1v1h-1zM3 12h1v1h-1zM6 12h1v1h-1zM8 12h1v1h-1zM11 12h1v1h-1zM3 13h4v1h-4zM8 13h4v1h-4z";

// Software_Statistics_Stats_Graphs_Bars.png
const SPRITE_SOFTWARE_STATISTICS_STATS_GRAPHS_BARS =
  "M5 2h5v1h-5zM5 3h1v1h-1zM9 3h1v1h-1zM5 4h1v1h-1zM9 4h5v1h-5zM5 5h1v1h-1zM9 5h1v1h-1zM13 5h1v1h-1zM1 6h5v1h-5zM9 6h1v1h-1zM13 6h1v1h-1zM1 7h1v1h-1zM5 7h1v1h-1zM9 7h1v1h-1zM13 7h1v1h-1zM1 8h1v1h-1zM5 8h1v1h-1zM9 8h1v1h-1zM13 8h1v1h-1zM1 9h1v1h-1zM5 9h1v1h-1zM9 9h1v1h-1zM13 9h1v1h-1zM1 10h1v1h-1zM5 10h1v1h-1zM9 10h1v1h-1zM13 10h1v1h-1zM1 11h1v1h-1zM5 11h1v1h-1zM9 11h1v1h-1zM13 11h1v1h-1zM1 12h1v1h-1zM5 12h1v1h-1zM9 12h1v1h-1zM13 12h1v1h-1zM1 13h13v1h-13z";

// Travel_Car_Driving_Speedometer_Graph.png
const SPRITE_TRAVEL_CAR_DRIVING_SPEEDOMETER_GRAPH =
  "M5 3h5v1h-5zM3 4h3v1h-3zM9 4h5v1h-5zM2 5h2v1h-2zM11 5h1v1h-1zM13 5h1v1h-1zM1 6h2v1h-2zM5 6h3v1h-3zM10 6h1v1h-1zM12 6h2v1h-2zM1 7h1v1h-1zM4 7h2v1h-2zM7 7h3v1h-3zM12 7h2v1h-2zM0 8h2v1h-2zM3 8h2v1h-2zM7 8h2v1h-2zM11 8h1v1h-1zM13 8h2v1h-2zM0 9h1v1h-1zM2 9h2v1h-2zM6 9h2v1h-2zM10 9h1v1h-1zM14 9h1v1h-1zM0 10h1v1h-1zM2 10h1v1h-1zM5 10h2v1h-2zM9 10h2v1h-2zM14 10h1v1h-1zM0 11h1v1h-1zM2 11h1v1h-1zM5 11h1v1h-1zM8 11h3v1h-3zM14 11h1v1h-1zM0 12h3v1h-3zM5 12h4v1h-4zM10 12h5v1h-5z";

// Map_Markers_Scanner_Sweep_Radar_Detection.png
const SPRITE_MAP_MARKERS_SCANNER_SWEEP_RADAR_DETECTION =
  "M5 0h6v1h-6zM3 1h3v1h-3zM7 1h1v1h-1zM10 1h3v1h-3zM2 2h8v1h-8zM12 2h2v1h-2zM1 3h2v1h-2zM4 3h8v1h-8zM13 3h2v1h-2zM1 4h1v1h-1zM5 4h8v1h-8zM14 4h1v1h-1zM0 5h2v1h-2zM6 5h7v1h-7zM14 5h2v1h-2zM0 6h1v1h-1zM7 6h7v1h-7zM15 6h1v1h-1zM0 7h1v1h-1zM2 7h1v1h-1zM4 7h1v1h-1zM8 7h6v1h-6zM15 7h1v1h-1zM0 8h1v1h-1zM8 8h1v1h-1zM10 8h4v1h-4zM15 8h1v1h-1zM0 9h1v1h-1zM2 9h1v1h-1zM4 9h1v1h-1zM6 9h1v1h-1zM8 9h6v1h-6zM15 9h1v1h-1zM0 10h2v1h-2zM3 10h1v1h-1zM5 10h1v1h-1zM7 10h2v1h-2zM10 10h1v1h-1zM12 10h1v1h-1zM14 10h2v1h-2zM1 11h1v1h-1zM4 11h1v1h-1zM6 11h1v1h-1zM8 11h5v1h-5zM14 11h1v1h-1zM1 12h2v1h-2zM5 12h1v1h-1zM7 12h2v1h-2zM10 12h1v1h-1zM13 12h2v1h-2zM2 13h2v1h-2zM6 13h1v1h-1zM8 13h2v1h-2zM12 13h2v1h-2zM3 14h3v1h-3zM10 14h3v1h-3zM5 15h6v1h-6z";

// Travel_Bell_Alarm_Alert_Disaster.png
const SPRITE_TRAVEL_BELL_ALARM_ALERT_DISASTER =
  "M5 1h5v1h-5zM5 2h1v1h-1zM9 2h2v1h-2zM4 3h2v1h-2zM7 3h2v1h-2zM10 3h2v1h-2zM3 4h2v1h-2zM8 4h2v1h-2zM11 4h2v1h-2zM2 5h2v1h-2zM9 5h2v1h-2zM12 5h2v1h-2zM1 6h2v1h-2zM10 6h2v1h-2zM13 6h1v1h-1zM1 7h1v1h-1zM5 7h3v1h-3zM11 7h1v1h-1zM13 7h2v1h-2zM1 8h1v1h-1zM5 8h1v1h-1zM7 8h1v1h-1zM11 8h1v1h-1zM14 8h1v1h-1zM1 9h1v1h-1zM5 9h3v1h-3zM11 9h1v1h-1zM14 9h1v1h-1zM1 10h2v1h-2zM10 10h5v1h-5zM2 11h2v1h-2zM9 11h2v1h-2zM3 12h2v1h-2zM8 12h2v1h-2zM4 13h5v1h-5z";

// Tools_Crafting_Books_Scroll_Paper_Document.png
const SPRITE_TOOLS_CRAFTING_BOOKS_SCROLL_PAPER_DOCUMENT =
  "M1 1h4v1h-4zM10 1h4v1h-4zM0 2h2v1h-2zM4 2h1v1h-1zM10 2h1v1h-1zM13 2h2v1h-2zM0 3h1v1h-1zM3 3h9v1h-9zM14 3h1v1h-1zM0 4h1v1h-1zM3 4h1v1h-1zM11 4h1v1h-1zM14 4h1v1h-1zM0 5h1v1h-1zM3 5h1v1h-1zM5 5h5v1h-5zM11 5h1v1h-1zM14 5h1v1h-1zM0 6h1v1h-1zM3 6h1v1h-1zM11 6h1v1h-1zM14 6h1v1h-1zM0 7h1v1h-1zM3 7h1v1h-1zM5 7h5v1h-5zM11 7h1v1h-1zM14 7h1v1h-1zM0 8h1v1h-1zM3 8h1v1h-1zM11 8h1v1h-1zM14 8h1v1h-1zM0 9h1v1h-1zM3 9h1v1h-1zM5 9h5v1h-5zM11 9h1v1h-1zM14 9h1v1h-1zM0 10h1v1h-1zM3 10h1v1h-1zM11 10h1v1h-1zM14 10h1v1h-1zM0 11h1v1h-1zM2 11h2v1h-2zM5 11h5v1h-5zM11 11h2v1h-2zM14 11h1v1h-1zM0 12h2v1h-2zM13 12h2v1h-2zM1 13h13v1h-13z";

// Software_Hourglass_Sand_Time_Wait.png
const SPRITE_SOFTWARE_HOURGLASS_SAND_TIME_WAIT =
  "M2 0h11v1h-11zM2 1h1v1h-1zM12 1h1v1h-1zM2 2h11v1h-11zM3 3h1v1h-1zM11 3h1v1h-1zM3 4h1v1h-1zM5 4h5v1h-5zM11 4h1v1h-1zM3 5h1v1h-1zM5 5h2v1h-2zM8 5h2v1h-2zM11 5h1v1h-1zM3 6h2v1h-2zM6 6h3v1h-3zM10 6h2v1h-2zM4 7h2v1h-2zM7 7h1v1h-1zM9 7h2v1h-2zM3 8h2v1h-2zM6 8h3v1h-3zM10 8h2v1h-2zM3 9h1v1h-1zM5 9h2v1h-2zM8 9h2v1h-2zM11 9h1v1h-1zM3 10h1v1h-1zM5 10h5v1h-5zM11 10h1v1h-1zM3 11h1v1h-1zM11 11h1v1h-1zM2 12h11v1h-11zM2 13h1v1h-1zM12 13h1v1h-1zM2 14h11v1h-11z";

// Software_Options_Settings_Cogwheel_Gear_Mechanics.png
const SPRITE_SOFTWARE_OPTIONS_SETTINGS_COGWHEEL_GEAR_MECHANICS =
  "M4 2h8v1h-8zM4 3h1v1h-1zM7 3h2v1h-2zM11 3h1v1h-1zM2 4h3v1h-3zM11 4h3v1h-3zM2 5h1v1h-1zM13 5h1v1h-1zM2 6h1v1h-1zM7 6h2v1h-2zM13 6h1v1h-1zM2 7h2v1h-2zM6 7h4v1h-4zM12 7h2v1h-2zM2 8h2v1h-2zM6 8h4v1h-4zM12 8h2v1h-2zM2 9h1v1h-1zM7 9h2v1h-2zM13 9h1v1h-1zM2 10h1v1h-1zM13 10h1v1h-1zM2 11h3v1h-3zM11 11h3v1h-3zM4 12h1v1h-1zM7 12h2v1h-2zM11 12h1v1h-1zM4 13h8v1h-8z";

// Software_Magnifier_Zoom_Looking_Magnifying_Glass.png
const SPRITE_SOFTWARE_MAGNIFIER_ZOOM_LOOKING_MAGNIFYING_GLASS =
  "M3 0h7v1h-7zM2 1h2v1h-2zM9 1h2v1h-2zM1 2h2v1h-2zM10 2h2v1h-2zM0 3h2v1h-2zM5 3h3v1h-3zM11 3h2v1h-2zM0 4h1v1h-1zM4 4h5v1h-5zM12 4h1v1h-1zM0 5h1v1h-1zM3 5h2v1h-2zM6 5h1v1h-1zM8 5h2v1h-2zM12 5h1v1h-1zM0 6h1v1h-1zM3 6h4v1h-4zM9 6h1v1h-1zM12 6h1v1h-1zM0 7h1v1h-1zM3 7h2v1h-2zM8 7h2v1h-2zM12 7h1v1h-1zM0 8h1v1h-1zM4 8h2v1h-2zM7 8h2v1h-2zM12 8h1v1h-1zM0 9h2v1h-2zM5 9h3v1h-3zM11 9h2v1h-2zM1 10h2v1h-2zM10 10h1v1h-1zM12 10h2v1h-2zM2 11h2v1h-2zM9 11h1v1h-1zM13 11h2v1h-2zM3 12h8v1h-8zM14 12h2v1h-2zM10 13h2v1h-2zM15 13h1v1h-1zM11 14h2v1h-2zM14 14h2v1h-2zM12 15h3v1h-3z";

// Travel_Bell_Notification_Ringing.png
const SPRITE_TRAVEL_BELL_NOTIFICATION_RINGING =
  "M6 1h3v1h-3zM4 2h3v1h-3zM8 2h3v1h-3zM3 3h2v1h-2zM10 3h2v1h-2zM3 4h1v1h-1zM11 4h1v1h-1zM3 5h1v1h-1zM11 5h1v1h-1zM3 6h1v1h-1zM11 6h1v1h-1zM3 7h1v1h-1zM11 7h1v1h-1zM2 8h2v1h-2zM11 8h2v1h-2zM2 9h1v1h-1zM12 9h1v1h-1zM1 10h13v1h-13zM1 11h1v1h-1zM13 11h1v1h-1zM1 12h13v1h-13zM5 13h1v1h-1zM9 13h1v1h-1zM5 14h5v1h-5z";

// Travel_Person_Player_Character_Single.png
const SPRITE_TRAVEL_PERSON_PLAYER_CHARACTER_SINGLE =
  "M5 1h5v1h-5zM4 2h2v1h-2zM9 2h2v1h-2zM4 3h1v1h-1zM10 3h1v1h-1zM4 4h1v1h-1zM10 4h1v1h-1zM4 5h1v1h-1zM10 5h1v1h-1zM4 6h2v1h-2zM9 6h2v1h-2zM4 7h7v1h-7zM3 8h2v1h-2zM10 8h2v1h-2zM2 9h2v1h-2zM11 9h2v1h-2zM2 10h1v1h-1zM12 10h1v1h-1zM2 11h1v1h-1zM12 11h1v1h-1zM2 12h1v1h-1zM12 12h1v1h-1zM2 13h11v1h-11z";

// Weather_Moon_Night_Crescent_Darkness_Mode_Twilight_Small.png
const SPRITE_WEATHER_MOON_NIGHT_CRESCENT_DARKNESS_MODE_TWILIGHT_SMALL =
  "M4 2h7v1h-7zM3 3h2v1h-2zM10 3h2v1h-2zM2 4h2v1h-2zM11 4h2v1h-2zM2 5h1v1h-1zM8 5h3v1h-3zM12 5h1v1h-1zM2 6h1v1h-1zM7 6h2v1h-2zM10 6h3v1h-3zM2 7h1v1h-1zM7 7h1v1h-1zM2 8h1v1h-1zM7 8h2v1h-2zM10 8h3v1h-3zM2 9h1v1h-1zM8 9h3v1h-3zM12 9h1v1h-1zM2 10h2v1h-2zM11 10h2v1h-2zM3 11h2v1h-2zM10 11h2v1h-2zM4 12h7v1h-7z";

// Software_Monitor_Display_Brightness_Sun.png
const SPRITE_SOFTWARE_MONITOR_DISPLAY_BRIGHTNESS_SUN =
  "M5 1h6v1h-6zM2 2h4v1h-4zM7 2h2v1h-2zM10 2h4v1h-4zM2 3h1v1h-1zM4 3h2v1h-2zM10 3h2v1h-2zM13 3h1v1h-1zM2 4h2v1h-2zM6 4h4v1h-4zM12 4h2v1h-2zM1 5h3v1h-3zM5 5h2v1h-2zM9 5h2v1h-2zM12 5h3v1h-3zM1 6h1v1h-1zM4 6h2v1h-2zM10 6h2v1h-2zM14 6h1v1h-1zM1 7h2v1h-2zM4 7h1v1h-1zM11 7h1v1h-1zM13 7h2v1h-2zM1 8h2v1h-2zM4 8h1v1h-1zM11 8h1v1h-1zM13 8h2v1h-2zM1 9h1v1h-1zM4 9h2v1h-2zM10 9h2v1h-2zM14 9h1v1h-1zM1 10h3v1h-3zM5 10h2v1h-2zM9 10h2v1h-2zM12 10h3v1h-3zM2 11h2v1h-2zM6 11h4v1h-4zM12 11h2v1h-2zM2 12h1v1h-1zM4 12h2v1h-2zM10 12h2v1h-2zM13 12h1v1h-1zM2 13h4v1h-4zM7 13h2v1h-2zM10 13h4v1h-4zM5 14h6v1h-6z";

// Tools_Crafting_Books_Manual_Codex_Instructions_Tutorial_Documentation.png
const SPRITE_TOOLS_CRAFTING_BOOKS_MANUAL_CODEX_INSTRUCTIONS_TUTORIAL_DOCUMENTATION =
  "M2 2h4v1h-4zM9 2h4v1h-4zM0 3h3v1h-3zM5 3h5v1h-5zM12 3h3v1h-3zM0 4h1v1h-1zM2 4h1v1h-1zM7 4h1v1h-1zM12 4h1v1h-1zM14 4h1v1h-1zM0 5h1v1h-1zM2 5h1v1h-1zM7 5h1v1h-1zM12 5h1v1h-1zM14 5h1v1h-1zM0 6h1v1h-1zM2 6h1v1h-1zM7 6h1v1h-1zM12 6h1v1h-1zM14 6h1v1h-1zM0 7h1v1h-1zM2 7h1v1h-1zM7 7h1v1h-1zM12 7h1v1h-1zM14 7h1v1h-1zM0 8h1v1h-1zM2 8h1v1h-1zM7 8h1v1h-1zM12 8h1v1h-1zM14 8h1v1h-1zM0 9h1v1h-1zM2 9h1v1h-1zM7 9h1v1h-1zM12 9h1v1h-1zM14 9h1v1h-1zM0 10h1v1h-1zM2 10h3v1h-3zM7 10h1v1h-1zM10 10h3v1h-3zM14 10h1v1h-1zM0 11h1v1h-1zM5 11h1v1h-1zM7 11h1v1h-1zM9 11h1v1h-1zM14 11h1v1h-1zM0 12h5v1h-5zM6 12h3v1h-3zM10 12h5v1h-5zM4 13h2v1h-2zM9 13h2v1h-2zM5 14h5v1h-5z";

// Software_Exit_Quit_Doorway_Button.png
const SPRITE_SOFTWARE_EXIT_QUIT_DOORWAY_BUTTON =
  "M2 2h9v1h-9zM2 3h1v1h-1zM10 3h1v1h-1zM2 4h1v1h-1zM4 4h8v1h-8zM2 5h1v1h-1zM6 5h4v1h-4zM11 5h2v1h-2zM2 6h1v1h-1zM7 6h1v1h-1zM12 6h2v1h-2zM2 7h1v1h-1zM7 7h1v1h-1zM13 7h1v1h-1zM2 8h1v1h-1zM7 8h1v1h-1zM12 8h2v1h-2zM2 9h1v1h-1zM7 9h3v1h-3zM11 9h2v1h-2zM2 10h1v1h-1zM7 10h5v1h-5zM2 11h1v1h-1zM10 11h1v1h-1zM2 12h2v1h-2zM7 12h4v1h-4zM3 13h3v1h-3zM7 13h1v1h-1zM5 14h3v1h-3z";

// Software_Signs_Maths_Plus_Addition_Bonus_Add_New.png
const SPRITE_SOFTWARE_SIGNS_MATHS_PLUS_ADDITION_BONUS_ADD_NEW =
  "M6 2h4v1h-4zM6 3h1v1h-1zM9 3h1v1h-1zM6 4h1v1h-1zM9 4h1v1h-1zM6 5h1v1h-1zM9 5h1v1h-1zM2 6h5v1h-5zM9 6h5v1h-5zM2 7h1v1h-1zM13 7h1v1h-1zM2 8h1v1h-1zM13 8h1v1h-1zM2 9h5v1h-5zM9 9h5v1h-5zM6 10h1v1h-1zM9 10h1v1h-1zM6 11h1v1h-1zM9 11h1v1h-1zM6 12h1v1h-1zM9 12h1v1h-1zM6 13h4v1h-4z";

// --- Onboarding wizard ---
// Controller_Buttons_Menu_Options_Settings.png
export function PixelIconProgram({ size = 32, className }: IconProps) {
  return <PixelSvg size={size} className={className} d={SPRITE_CONTROLLER_BUTTONS_MENU_OPTIONS_SETTINGS} />;
}

// Software_Speech_Bubble_Three_Dots_Dialogue.png
export function PixelIconChannels({ size = 32, className }: IconProps) {
  return <PixelSvg size={size} className={className} d={SPRITE_SOFTWARE_SPEECH_BUBBLE_THREE_DOTS_DIALOGUE} />;
}

// Software_File_Document_Page_Text_Word.png
export function PixelIconDocs({ size = 32, className }: IconProps) {
  return <PixelSvg size={size} className={className} d={SPRITE_SOFTWARE_FILE_DOCUMENT_PAGE_TEXT_WORD} />;
}

// Travel_Person_Player_Character_Three_People_Multiplayer.png
export function PixelIconHelpers({ size = 32, className }: IconProps) {
  return <PixelSvg size={size} className={className} d={SPRITE_TRAVEL_PERSON_PLAYER_CHARACTER_THREE_PEOPLE_MULTIPLAYER} />;
}

// Software_Email_Message_Send_Paper_Plane.png
export function PixelIconLaunch({ size = 32, className }: IconProps) {
  return <PixelSvg size={size} className={className} d={SPRITE_SOFTWARE_EMAIL_MESSAGE_SEND_PAPER_PLANE} />;
}

// Software_Notepad_Wordpad_Text_Editor.png
export function PixelIconNotion({ size = 32, className }: IconProps) {
  return <PixelSvg size={size} className={className} d={SPRITE_SOFTWARE_NOTEPAD_WORDPAD_TEXT_EDITOR} />;
}

// Platforms_GitHub.png
export function PixelIconGitHub({ size = 32, className }: IconProps) {
  return <PixelSvg size={size} className={className} d={SPRITE_PLATFORMS_GITHUB} />;
}

// Software_File_Document_Page_Text_Word.png
export function PixelIconGoogleDoc({ size = 32, className }: IconProps) {
  return <PixelSvg size={size} className={className} d={SPRITE_SOFTWARE_FILE_DOCUMENT_PAGE_TEXT_WORD} />;
}

// Software_Internet_Upload_from_Disk.png
export function PixelIconMarkdown({ size = 32, className }: IconProps) {
  return <PixelSvg size={size} className={className} d={SPRITE_SOFTWARE_INTERNET_UPLOAD_FROM_DISK} />;
}

// Software_File_Document_Page_Plus_Add_New.png
export function PixelIconDropFile({ size = 32, className }: IconProps) {
  return <PixelSvg size={size} className={className} d={SPRITE_SOFTWARE_FILE_DOCUMENT_PAGE_PLUS_ADD_NEW} />;
}

// Software_Storage_Drives_Discs_Disks_Server_1.png
export function PixelIconStorage({ size = 32, className }: IconProps) {
  return <PixelSvg size={size} className={className} d={SPRITE_SOFTWARE_STORAGE_DRIVES_DISCS_DISKS_SERVER_1} />;
}

// Software_Hardware_Monitor_Display_PC_Computer.png
export function PixelIconMonitor({ size = 32, className }: IconProps) {
  return <PixelSvg size={size} className={className} d={SPRITE_SOFTWARE_HARDWARE_MONITOR_DISPLAY_PC_COMPUTER} />;
}

// RPG_Magic_Sparkles_Enchantment.png
export function PixelIconSparkle({ size = 32, className }: IconProps) {
  return <PixelSvg size={size} className={className} d={SPRITE_RPG_MAGIC_SPARKLES_ENCHANTMENT} />;
}

// Software_Checkbox_Checkmarked_Yes_Done_Todo.png
export function PixelIconCheck({ size = 32, className }: IconProps) {
  return <PixelSvg size={size} className={className} d={SPRITE_SOFTWARE_CHECKBOX_CHECKMARKED_YES_DONE_TODO} />;
}

// Software_Warning_Sign_Triangle_Exclaimation_Mark_Error.png
export function PixelIconWarning({ size = 32, className }: IconProps) {
  return <PixelSvg size={size} className={className} d={SPRITE_SOFTWARE_WARNING_SIGN_TRIANGLE_EXCLAIMATION_MARK_ERROR} />;
}

// Software_Clock_Time_Wait_2.png
export function PixelIconClock({ size = 32, className }: IconProps) {
  return <PixelSvg size={size} className={className} d={SPRITE_SOFTWARE_CLOCK_TIME_WAIT_2} />;
}

// Software_Warning_Sign_Circle_Information_Help.png
export function PixelIconInfo({ size = 32, className }: IconProps) {
  return <PixelSvg size={size} className={className} d={SPRITE_SOFTWARE_WARNING_SIGN_CIRCLE_INFORMATION_HELP} />;
}

// Tools_Crafting_Padlock_Locked.png
export function PixelIconLock({ size = 32, className }: IconProps) {
  return <PixelSvg size={size} className={className} d={SPRITE_TOOLS_CRAFTING_PADLOCK_LOCKED} />;
}

// Software_Clipbaord_List_File_Copy_Paste.png
export function PixelIconClipboard({ size = 32, className }: IconProps) {
  return <PixelSvg size={size} className={className} d={SPRITE_SOFTWARE_CLIPBAORD_LIST_FILE_COPY_PASTE} />;
}

// Software_Signs_Maths_Multiplication_X_Crossout_Checkmark_Cancel.png
export function PixelIconClose({ size = 32, className }: IconProps) {
  return <PixelSvg size={size} className={className} d={SPRITE_SOFTWARE_SIGNS_MATHS_MULTIPLICATION_X_CROSSOUT_CHECKMARK_CANCEL} />;
}

// Arrows_Left_West.png
export function PixelIconArrowLeft({ size = 32, className }: IconProps) {
  return <PixelSvg size={size} className={className} d={SPRITE_ARROWS_LEFT_WEST} />;
}

// Arrows_Right_East.png
export function PixelIconArrowRight({ size = 32, className }: IconProps) {
  return <PixelSvg size={size} className={className} d={SPRITE_ARROWS_RIGHT_EAST} />;
}

// --- Dashboard ---
// Map_Markers_Building_Home_House.png
export function PixelIconHome({ size = 32, className }: IconProps) {
  return <PixelSvg size={size} className={className} d={SPRITE_MAP_MARKERS_BUILDING_HOME_HOUSE} />;
}

// Software_File_Folder_Directory_Explorer.png
export function PixelIconGrid({ size = 32, className }: IconProps) {
  return <PixelSvg size={size} className={className} d={SPRITE_SOFTWARE_FILE_FOLDER_DIRECTORY_EXPLORER} />;
}

// Tools_Crafting_Key_Unlock_1.png
export function PixelIconKey({ size = 32, className }: IconProps) {
  return <PixelSvg size={size} className={className} d={SPRITE_TOOLS_CRAFTING_KEY_UNLOCK_1} />;
}

// Software_Speech_Bubble_Question_Mark_Quest_Return_Finished.png
export function PixelIconChat({ size = 32, className }: IconProps) {
  return <PixelSvg size={size} className={className} d={SPRITE_SOFTWARE_SPEECH_BUBBLE_QUESTION_MARK_QUEST_RETURN_FINISHED} />;
}

// Tools_Crafting_Books_Manual_Documentation_Reading.png
export function PixelIconDoc({ size = 32, className }: IconProps) {
  return <PixelSvg size={size} className={className} d={SPRITE_TOOLS_CRAFTING_BOOKS_MANUAL_DOCUMENTATION_READING} />;
}

// Software_Speech_Bubble_Exclaimation_Mark_Quest_New.png
export function PixelIconGaps({ size = 32, className }: IconProps) {
  return <PixelSvg size={size} className={className} d={SPRITE_SOFTWARE_SPEECH_BUBBLE_EXCLAIMATION_MARK_QUEST_NEW} />;
}

// Travel_Person_Player_Character_Three_People_Multiplayer.png
export function PixelIconUsers({ size = 32, className }: IconProps) {
  return <PixelSvg size={size} className={className} d={SPRITE_TRAVEL_PERSON_PLAYER_CHARACTER_THREE_PEOPLE_MULTIPLAYER} />;
}

// Travel_Person_People_Two.png
export function PixelIconPeople({ size = 32, className }: IconProps) {
  return <PixelSvg size={size} className={className} d={SPRITE_TRAVEL_PERSON_PEOPLE_TWO} />;
}

// Software_Clipbaord_List_File_Copy_Paste.png
export function PixelIconMacro({ size = 32, className }: IconProps) {
  return <PixelSvg size={size} className={className} d={SPRITE_SOFTWARE_CLIPBAORD_LIST_FILE_COPY_PASTE} />;
}

// Software_Statistics_Stats_Graphs_Bars.png
export function PixelIconBars({ size = 32, className }: IconProps) {
  return <PixelSvg size={size} className={className} d={SPRITE_SOFTWARE_STATISTICS_STATS_GRAPHS_BARS} />;
}

// Travel_Car_Driving_Speedometer_Graph.png
export function PixelIconGauge({ size = 32, className }: IconProps) {
  return <PixelSvg size={size} className={className} d={SPRITE_TRAVEL_CAR_DRIVING_SPEEDOMETER_GRAPH} />;
}

// Map_Markers_Scanner_Sweep_Radar_Detection.png
export function PixelIconRadar({ size = 32, className }: IconProps) {
  return <PixelSvg size={size} className={className} d={SPRITE_MAP_MARKERS_SCANNER_SWEEP_RADAR_DETECTION} />;
}

// Software_Warning_Sign_Triangle_Exclaimation_Mark_Error.png
export function PixelIconAlert({ size = 32, className }: IconProps) {
  return <PixelSvg size={size} className={className} d={SPRITE_SOFTWARE_WARNING_SIGN_TRIANGLE_EXCLAIMATION_MARK_ERROR} />;
}

// Travel_Bell_Alarm_Alert_Disaster.png
export function PixelIconSiren({ size = 32, className }: IconProps) {
  return <PixelSvg size={size} className={className} d={SPRITE_TRAVEL_BELL_ALARM_ALERT_DISASTER} />;
}

// Tools_Crafting_Books_Scroll_Paper_Document.png
export function PixelIconLog({ size = 32, className }: IconProps) {
  return <PixelSvg size={size} className={className} d={SPRITE_TOOLS_CRAFTING_BOOKS_SCROLL_PAPER_DOCUMENT} />;
}

// Software_Hourglass_Sand_Time_Wait.png
export function PixelIconHourglass({ size = 32, className }: IconProps) {
  return <PixelSvg size={size} className={className} d={SPRITE_SOFTWARE_HOURGLASS_SAND_TIME_WAIT} />;
}

// Software_Options_Settings_Cogwheel_Gear_Mechanics.png
export function PixelIconGear({ size = 32, className }: IconProps) {
  return <PixelSvg size={size} className={className} d={SPRITE_SOFTWARE_OPTIONS_SETTINGS_COGWHEEL_GEAR_MECHANICS} />;
}

// Software_Magnifier_Zoom_Looking_Magnifying_Glass.png
export function PixelIconSearch({ size = 32, className }: IconProps) {
  return <PixelSvg size={size} className={className} d={SPRITE_SOFTWARE_MAGNIFIER_ZOOM_LOOKING_MAGNIFYING_GLASS} />;
}

// Travel_Bell_Notification_Ringing.png
export function PixelIconBell({ size = 32, className }: IconProps) {
  return <PixelSvg size={size} className={className} d={SPRITE_TRAVEL_BELL_NOTIFICATION_RINGING} />;
}

// Arrows_Right_East.png
export function PixelIconChevronRight({ size = 32, className }: IconProps) {
  return <PixelSvg size={size} className={className} d={SPRITE_ARROWS_RIGHT_EAST} />;
}

// Travel_Person_Player_Character_Single.png
export function PixelIconHand({ size = 32, className }: IconProps) {
  return <PixelSvg size={size} className={className} d={SPRITE_TRAVEL_PERSON_PLAYER_CHARACTER_SINGLE} />;
}

// Weather_Moon_Night_Crescent_Darkness_Mode_Twilight_Small.png
export function PixelIconMoon({ size = 32, className }: IconProps) {
  return <PixelSvg size={size} className={className} d={SPRITE_WEATHER_MOON_NIGHT_CRESCENT_DARKNESS_MODE_TWILIGHT_SMALL} />;
}

// Software_Monitor_Display_Brightness_Sun.png
export function PixelIconSun({ size = 32, className }: IconProps) {
  return <PixelSvg size={size} className={className} d={SPRITE_SOFTWARE_MONITOR_DISPLAY_BRIGHTNESS_SUN} />;
}

// Tools_Crafting_Books_Manual_Codex_Instructions_Tutorial_Documentation.png
export function PixelIconBook({ size = 32, className }: IconProps) {
  return <PixelSvg size={size} className={className} d={SPRITE_TOOLS_CRAFTING_BOOKS_MANUAL_CODEX_INSTRUCTIONS_TUTORIAL_DOCUMENTATION} />;
}

// Software_Exit_Quit_Doorway_Button.png
export function PixelIconExit({ size = 32, className }: IconProps) {
  return <PixelSvg size={size} className={className} d={SPRITE_SOFTWARE_EXIT_QUIT_DOORWAY_BUTTON} />;
}

// Software_Signs_Maths_Plus_Addition_Bonus_Add_New.png
export function PixelIconPlus({ size = 32, className }: IconProps) {
  return <PixelSvg size={size} className={className} d={SPRITE_SOFTWARE_SIGNS_MATHS_PLUS_ADDITION_BONUS_ADD_NEW} />;
}
