// Differential pin of lib/retrieve.js observable behavior (pre-rewrite).
// Fixture corpora are curated in-file: AI/software/generic, hardware
// prohibition, firmware rule, README rule, disclosure, consequence,
// returned/resubmit, referral+expiry, deflation/hours, software-vs-hardware
// isolation passages. Must pass UNMODIFIED after the stage split.
const { test } = require("node:test");
const assert = require("node:assert/strict");
const retrieve = require("./retrieve");

const CORPUS = [
  ["AI Policy", `## General AI Allowance
You can use AI tools like ChatGPT or GitHub Copilot for up to 30% of your project's code for syntax assistance, debugging, and boilerplate code.

## Be honest about AI
Always be honest about AI usage and use AI tools responsibly when building your project.

## Hardware CAD and PCB AI Prohibition
The 30% AI rule does not apply to hardware design. For hardware projects, all CAD assemblies, 3D models (.step files), and PCB designs/schematics must be 100% original, custom designs by you, not generated by AI (0% AI). Submitting fully AI-generated design files will result in rejection and may lead to a permanent ban.

## Firmware AI Rule
For firmware (microcontroller code), AI is permitted only under the standard software code limit of up to 30% with honest disclosure, but AI cannot generate your entire firmware.

## README AI Rule
Your project's README cannot be built by AI. You must write your own README by yourself.

## Disclosing AI Usage
You must disclose where and how AI was used in your project submission notes and README. Reviewers verify the AI percentage.

## Consequences of Exceeding the AI Limit or Hiding AI
If you exceed the 30% AI limit, reviewers will reject your project or reduce/deflate your payout and approved hours.
If you hide or do not disclose your AI usage, your project will be rejected and your payout penalized. Hiding AI usage is treated as dishonesty and fraud, which can lead to disciplinary action or a permanent ban from Hack Club programs.`],
  ["Review Guide", `## Spot-Check Verdicts and Returned Submissions
A returned submission (Needs Changes verdict) is not a penalty, fine, or final rejection. If your project is returned, you will receive reviewer feedback on what needs to be changed, and you can make adjustments and resubmit your project for review.

## Override Hours and Deflation
Reviewers may deflate approved hours when there is doubt about claimed hours or evidence does not support them. The unified database requires aggressive deflation when hours appear inflated and genuine effort is unclear. The audit checks indicators converge before hours are paid.`],
  ["Referral Guide", `## Referral Codes and Expiration
Referral codes expire in 48 hours (2 days) after being generated. Submitter referral links and codes must be redeemed within the 48-hour expiration window before they become invalid.`],
  ["Submission Guidelines", `## Software Requirements
For software projects, your repository must contain a README explaining what the project is, how to set it up or run it, and how it can be experienced. Software projects must have public open-source code on GitHub and a working playable URL.

## Hardware Requirements
For hardware projects, the repository must contain PCB schematics, wiring diagrams, CAD files in STEP format, and a bill of materials with specific part names.`],
];

const chunks = retrieve.chunkSections(CORPUS);
const index = retrieve.buildIndex(chunks);

function rankedFor(question) {
  return retrieve.score(index, retrieve.tokenize(question));
}

function checkRanking(question, expectedHeadings, expectedValues) {
  const ranked = rankedFor(question);
  assert.equal(ranked.length, expectedHeadings.length, `result count for: ${question}`);
  assert.deepEqual(ranked.map((r) => r.chunk.heading), expectedHeadings);
  assert.deepEqual(ranked.map((r) => r.value), expectedValues);
  return ranked;
}

/* (a) ranking order AND exact numeric scores: 13 queries, every boost/demote path */

test("general AI query: specific 30% cap outranks vague honesty (demoted x0.1)", () => {
  const ranked = checkRanking(
    "how much ai can i use in my code",
    [
      "Firmware AI Rule",
      "General AI Allowance",
      "Consequences of Exceeding the AI Limit or Hiding AI",
      "Software Requirements",
      "Referral Codes and Expiration",
      "Disclosing AI Usage",
      "Consequences of Exceeding the AI Limit or Hiding AI",
      "README AI Rule",
      "Be honest about AI",
    ],
    [
      10.429274923049451,
      9.377422770704746,
      5.904682714039018,
      4.137522830373351,
      1.899180885124585,
      0.8948002604732678,
      0.8765001897011541,
      0.8498047524513728,
      0.2962594708400881,
    ],
  );
  assert.match(ranked[0].chunk.text, /hard ceiling|30%/);
  assert.match(ranked[ranked.length - 1].chunk.text, /honest about AI/i);
});

test("hardware AI query: 0% CAD/PCB prohibition wins, generic allowance zeroed", () => {
  const ranked = checkRanking(
    "can i use ai to generate my pcb and cad files for hardware",
    [
      "Hardware CAD and PCB AI Prohibition",
      "Hardware Requirements",
      "Be honest about AI",
      "Consequences of Exceeding the AI Limit or Hiding AI",
      "Disclosing AI Usage",
      "Consequences of Exceeding the AI Limit or Hiding AI",
      "README AI Rule",
    ],
    [
      18.927989207179728,
      11.51606196446958,
      2.962594708400881,
      0.9046827140390187,
      0.8948002604732678,
      0.8765001897011541,
      0.8498047524513728,
    ],
  );
  assert.match(ranked[0].chunk.text, /not generated by ai/i);
  assert.equal(ranked.find((r) => /up to 30% of your project's code/i.test(r.chunk.text)), undefined);
});

test("firmware AI query: firmware rule wins, hardware prohibition demoted x0.1", () => {
  const ranked = checkRanking(
    "can ai generate firmware for microcontrollers",
    [
      "Firmware AI Rule",
      "Be honest about AI",
      "Consequences of Exceeding the AI Limit or Hiding AI",
      "Disclosing AI Usage",
      "Consequences of Exceeding the AI Limit or Hiding AI",
      "README AI Rule",
      "General AI Allowance",
      "Hardware CAD and PCB AI Prohibition",
    ],
    [
      15.200766844586715,
      0.9066118056275941,
      0.9046827140390187,
      0.8948002604732678,
      0.8765001897011541,
      0.8498047524513728,
      0.8226611117096827,
      0.0830568861930768,
    ],
  );
  assert.match(ranked[0].chunk.text, /standard software code limit/i);
});

test("firmware+pcb query stays on firmware path with prohibition demoted", () => {
  checkRanking(
    "can ai generate firmware pcb design",
    [
      "Firmware AI Rule",
      "Hardware Requirements",
      "Be honest about AI",
      "Consequences of Exceeding the AI Limit or Hiding AI",
      "Disclosing AI Usage",
      "Consequences of Exceeding the AI Limit or Hiding AI",
      "README AI Rule",
      "General AI Allowance",
      "Hardware CAD and PCB AI Prohibition",
    ],
    [
      12.929087601492725,
      1.8919417137222267,
      0.9066118056275941,
      0.9046827140390187,
      0.8948002604732678,
      0.8765001897011541,
      0.8498047524513728,
      0.8226611117096827,
      0.6451178571442058,
    ],
  );
});

test("README AI query: README prohibition wins, generic allowance zeroed", () => {
  const ranked = checkRanking(
    "can i use ai to write my project readme",
    [
      "README AI Rule",
      "Be honest about AI",
      "Disclosing AI Usage",
      "Software Requirements",
      "Consequences of Exceeding the AI Limit or Hiding AI",
      "Consequences of Exceeding the AI Limit or Hiding AI",
      "Hardware CAD and PCB AI Prohibition",
      "Spot-Check Verdicts and Returned Submissions",
      "Hardware Requirements",
    ],
    [
      12.309682135604191,
      3.3059200451997155,
      2.8255921589289477,
      1.8420021299290612,
      1.2108439679884953,
      1.1281751187952154,
      1.0465517101714896,
      0.37373605152980627,
      0.3159323577989279,
    ],
  );
  assert.match(ranked[0].chunk.text, /README cannot be built by AI/i);
  assert.equal(ranked.find((r) => /up to 30% of your project's code/i.test(r.chunk.text)), undefined);
});

test("disclosure AI query: disclosure chunk wins outright", () => {
  const ranked = checkRanking(
    "do i have to disclose ai usage in my submission",
    [
      "Disclosing AI Usage",
      "Consequences of Exceeding the AI Limit or Hiding AI",
      "Firmware AI Rule",
      "Spot-Check Verdicts and Returned Submissions",
      "Be honest about AI",
      "Consequences of Exceeding the AI Limit or Hiding AI",
      "README AI Rule",
      "Hardware CAD and PCB AI Prohibition",
      "General AI Allowance",
    ],
    [
      14.177823121444199,
      11.037517787087634,
      9.670345973329706,
      2.5918753073638574,
      2.561042248155734,
      0.9046827140390187,
      0.8498047524513728,
      0.830568861930768,
      0.8226611117096827,
    ],
  );
  assert.match(ranked[0].chunk.text, /disclose where and how AI was used/i);
});

test("consequence exceed query: exceed chunk first", () => {
  const ranked = checkRanking(
    "what happens if i exceed the ai limit",
    [
      "Consequences of Exceeding the AI Limit or Hiding AI",
      "Consequences of Exceeding the AI Limit or Hiding AI",
      "Hardware CAD and PCB AI Prohibition",
      "Firmware AI Rule",
      "Be honest about AI",
      "Disclosing AI Usage",
      "README AI Rule",
      "General AI Allowance",
    ],
    [
      11.531334425844847,
      8.611954511177734,
      6.830568861930768,
      2.2604126405347893,
      0.9066118056275941,
      0.8948002604732678,
      0.8498047524513728,
      0.8226611117096827,
    ],
  );
  assert.match(ranked[0].chunk.text, /If you exceed the 30% AI limit/i);
});

test("consequence hide/fraud query: hide chunk first", () => {
  const ranked = checkRanking(
    "what happens if i hide ai usage fraud ban",
    [
      "Consequences of Exceeding the AI Limit or Hiding AI",
      "Hardware CAD and PCB AI Prohibition",
      "Consequences of Exceeding the AI Limit or Hiding AI",
      "Disclosing AI Usage",
      "Be honest about AI",
      "Firmware AI Rule",
      "README AI Rule",
      "General AI Allowance",
    ],
    [
      14.02715287929612,
      8.123969015311781,
      6.904682714039018,
      2.992806499687131,
      2.561042248155734,
      0.850479307739872,
      0.8498047524513728,
      0.8226611117096827,
    ],
  );
  assert.match(ranked[0].chunk.text, /dishonesty and fraud/i);
});

test("returned query: feedback chunk boosted, deflation chunk zeroed", () => {
  const ranked = checkRanking(
    "what happens if my submission is returned can i resubmit is it a penalty",
    ["Spot-Check Verdicts and Returned Submissions", "Disclosing AI Usage"],
    [17.416792977173262, 1.9870672747473668],
  );
  assert.match(ranked[0].chunk.text, /not a penalty/i);
  assert.match(ranked[0].chunk.text, /resubmit/i);
  assert.equal(ranked.find((r) => /deflate/i.test(r.chunk.text)), undefined);
});

test("returned+hours query: deflation chunk survives when hours mentioned", () => {
  const ranked = checkRanking(
    "returned submission hours deflate claimed hours audit",
    [
      "Spot-Check Verdicts and Returned Submissions",
      "Override Hours and Deflation",
      "Consequences of Exceeding the AI Limit or Hiding AI",
      "Referral Codes and Expiration",
      "Disclosing AI Usage",
    ],
    [
      13.299374349065406,
      10.46843017520479,
      4.784113274713995,
      3.7432737074907307,
      1.9870672747473668,
    ],
  );
  assert.match(ranked[1].chunk.text, /deflate approved hours/i);
});

test("referral query: referral+expiry chunk wins across phrasing", () => {
  const ranked = checkRanking(
    "when does my referral code expire",
    [
      "Referral Codes and Expiration",
      "Firmware AI Rule",
      "Software Requirements",
      "General AI Allowance",
    ],
    [
      13.811928098687462,
      4.57879561530958,
      4.137522830373351,
      1.6628199452728354,
    ],
  );
  assert.match(ranked[0].chunk.text, /48 hours/i);
  assert.match(ranked[0].chunk.text, /2 days/i);
});

test("software domain query: software boosted, pure hardware zeroed", () => {
  const ranked = checkRanking(
    "what are the readme requirements for my software project",
    [
      "Software Requirements",
      "Firmware AI Rule",
      "README AI Rule",
      "Disclosing AI Usage",
      "Spot-Check Verdicts and Returned Submissions",
      "Be honest about AI",
      "General AI Allowance",
      "Consequences of Exceeding the AI Limit or Hiding AI",
      "Consequences of Exceeding the AI Limit or Hiding AI",
    ],
    [
      10.132663523728835,
      4.752143064925018,
      2.8397018925387276,
      1.9307918984556798,
      0.37373605152980627,
      0.3433253367988349,
      0.3159323577989279,
      0.3061612539494765,
      0.25167492909406125,
    ],
  );
  assert.equal(ranked.find((r) => /wiring diagram|\bpcb\b/i.test(r.chunk.text)), undefined);
});

test("hardware domain query: hardware wins, pure software zeroed", () => {
  const ranked = checkRanking(
    "what are the wiring diagram and pcb schematic requirements for hardware",
    ["Hardware Requirements", "Hardware CAD and PCB AI Prohibition"],
    [17.053946654476405, 9.15599688476491],
  );
  assert.match(ranked[0].chunk.text, /hardware/i);
  assert.equal(ranked.find((r) => /playable url/i.test(r.chunk.text)), undefined);
});

/* (b) chunkSection boundaries / headings / caps / domain-split */

test("chunkSection splits on headings and repeats heading into the body", () => {
  const doc = `## Exporting sprites\n\nExport your sprite as a PNG at native size.\n\n## Restoration energy\n\nRestoration energy, or RE, is earned by shipping approved sidequests.`;
  const out = retrieve.chunkSection("Pixl Docs", doc);
  assert.equal(out.length, 2);
  assert.deepEqual(out.map((c) => c.heading), ["Exporting sprites", "Restoration energy"]);
  assert.match(out[0].text, /Exporting sprites/);
  assert.match(out[0].text, /native size/);
});

test("chunkSection splits software vs hardware paragraphs at domain boundary", () => {
  const mixed = `## Project Guidelines\n\nFor software projects, your repository must have a clear README explaining how to run and experience the application.\n\nFor hardware projects, the repository must include PCB schematics, wiring diagrams, and CAD models in STEP format.`;
  const out = retrieve.chunkSection("Guidelines", mixed);
  assert.equal(out.length, 2);
  assert.equal(out[0].domain, "software");
  assert.equal(out[1].domain, "hardware");
  assert.doesNotMatch(out[0].text, /PCB schematics/);
  assert.doesNotMatch(out[1].text, /For software projects/);
});

test("chunkSection keeps lead-in paragraphs ending with colon together", () => {
  const doc = `## Hardware Requirements\n\nFor hardware projects, the repo must contain everything needed to build it from scratch. This means, at minimum:\n\n* PCB schematics and wiring diagrams\n* CAD files in STEP format\n* Bill of materials with part numbers`;
  const out = retrieve.chunkSection("Hardware Guide", doc);
  assert.equal(out.length, 1);
  assert.match(out[0].text, /This means, at minimum:/);
  assert.match(out[0].text, /PCB schematics and wiring diagrams/);
});

test("chunkSection splits oversized paragraphs on sentence ends within cap", () => {
  const long = Array.from({ length: 60 }, (_, i) => `Sentence number ${i} explains a detail about the thing.`).join(" ");
  const out = retrieve.chunkSection("Long", long);
  assert.equal(out.length, 4);
  assert.deepEqual(out.map((c) => c.text.length), [853, 863, 863, 647]);
  for (const c of out) {
    assert.ok(c.text.length <= retrieve.MAX_CHUNK);
    assert.match(c.text.trim(), /\.$/);
  }
});

test("chunkSection returns nothing for empty input and merges tiny neighbours", () => {
  assert.deepEqual(retrieve.chunkSection("Empty", ""), []);
  assert.deepEqual(retrieve.chunkSection("Empty", undefined), []);
  const small = retrieve.chunkSection("Tiny", "hi\n\nthere");
  assert.equal(small.length, 1);
});

/* (c) selectChunks budget stop rule (no skip-ahead) */

test("selectChunks stops at first chunk that does not fit, no skip-ahead", () => {
  const BIG = "gizmo ".repeat(40) + "widget contraption apparatus mechanism instrument.";
  const SMALL = "gizmo mentioned once, short.";
  const localIndex = retrieve.buildIndex(retrieve.chunkSections([["Big", BIG], ["Small", SMALL]]));
  const ranked = retrieve.score(localIndex, retrieve.tokenize("gizmo"));
  assert.equal(ranked.length, 2);
  assert.deepEqual(ranked.map((r) => r.value), [0.38243447628327687, 0.2772110553228252]);
  assert.deepEqual(ranked.map((r) => r.chunk.text.length), [290, 28]);
  assert.deepEqual(retrieve.selectChunks(localIndex, "gizmo", 33), []);
});

test("selectChunks respects the character budget", () => {
  const got = retrieve.selectChunks(index, "how much ai can i use in my code", 300);
  const total = got.reduce((sum, c) => sum + c.text.length, 0);
  assert.ok(total <= 300);
  assert.ok(got.length >= 1);
});

test("selectChunks returns nothing when no term matches", () => {
  assert.deepEqual(retrieve.selectChunks(index, "zzzz qqqq"), []);
  assert.deepEqual(retrieve.selectChunks(index, ""), []);
});

/* (d) selectContext: generated-first ordering, exclude-set, full-corpus fallback */

test("selectContext puts generated sections first, unranked, ahead of chunks", () => {
  const generated = [
    ["About pixie", "Q: Who are you?\nA: I'm pixie."],
    ["Program timeline", "Pixl launches at some point."],
  ];
  const ctx = retrieve.selectContext({
    generated,
    index,
    sources: CORPUS,
    question: "how much ai can i use in my code",
  });
  assert.ok(ctx.indexOf("### About pixie") < ctx.indexOf("### AI Policy"));
  assert.match(ctx, /I'm pixie/);
  assert.match(ctx, /Pixl launches at some point/);
  assert.match(ctx, /30%/);
});

test("selectContext exclude drops a banned source from chunks", () => {
  const localIndex = retrieve.buildIndex(
    retrieve.chunkSections([["Shop", "gizmo price 700 px in the shop catalogue"], ["Docs", "gizmo repair guide for broken widgets"]]),
  );
  const ctx = retrieve.selectContext({
    generated: [],
    index: localIndex,
    sources: [["Shop", "gizmo price 700 px"], ["Docs", "gizmo repair guide"]],
    question: "gizmo shop price",
    exclude: new Set(["Shop"]),
  });
  assert.equal(ctx, "### Docs\ngizmo repair guide for broken widgets");
});

test("selectContext fallback sends capped corpus when nothing matches, minus excluded", () => {
  const generated = [["About pixie", "identity text here"]];
  const ctx = retrieve.selectContext({
    generated,
    index,
    sources: CORPUS,
    question: "zzzz qqqq",
  });
  assert.match(ctx, /### About pixie/);
  assert.match(ctx, /General AI Allowance/);
  const fallback = retrieve.selectContext({
    generated: [],
    index,
    sources: [["Shop", "unrelated shop text"], ["Docs", "unrelated docs text"]],
    question: "zzzz qqqq",
    exclude: new Set(["Shop"]),
  });
  assert.doesNotMatch(fallback, /### Shop/);
  assert.match(fallback, /### Docs/);
});

/* (e) chunk metadata {source, heading, domain} */

test("chunks carry source, heading, and domain metadata", () => {
  const byHeading = new Map(chunks.map((c) => [c.heading, c]));
  assert.equal(byHeading.get("General AI Allowance").source, "AI Policy");
  assert.equal(byHeading.get("General AI Allowance").domain, "general");
  assert.equal(byHeading.get("Hardware CAD and PCB AI Prohibition").domain, "hardware");
  assert.equal(byHeading.get("Software Requirements").source, "Submission Guidelines");
  assert.equal(byHeading.get("Software Requirements").domain, "software");
  assert.equal(byHeading.get("Hardware Requirements").domain, "hardware");
  assert.equal(byHeading.get("Referral Codes and Expiration").source, "Referral Guide");
  assert.equal(byHeading.get("Spot-Check Verdicts and Returned Submissions").source, "Review Guide");
  for (const c of chunks) {
    assert.ok(typeof c.source === "string" && c.source.length > 0);
    assert.ok(typeof c.heading === "string" && c.heading.length > 0);
    assert.ok(["software", "hardware", "general"].includes(c.domain));
  }
});

test("detectDomain classifies software, hardware, and general", () => {
  assert.equal(retrieve.detectDomain("A web app built with React, deployed on Vercel with a github repo"), "software");
  assert.equal(retrieve.detectDomain("Design a custom PCB with KiCad, route traces, and export Gerber files"), "hardware");
  assert.equal(retrieve.detectDomain("General community guidelines and age requirements for participants"), "general");
});
