// Score stage: BM25 over chunks plus rule boosts and demotions.
// Standard BM25 constants. k1 damps how much a repeated term keeps helping, b
// controls how hard a long chunk gets penalised for its length.
const K1 = 1.2;
const B = 0.75;

// A deciding rule (hardware 0% AI, README ban, referral expiry) must outrank any
// number of generic BM25 matches, or the generic allowance wins by word count.
const BOOST_DECIDING_RULE = 6.0;
// The specific 30% cap must beat vague AI mentions, but stays below a deciding
// prohibition so hardware/README rules still win outright.
const BOOST_SPECIFIC_CAP = 5.0;
// Returned-submission feedback must beat deflation chatter for the same words.
const BOOST_RETURNED_RULE = 5.0;
// Domain isolation (+software/-hardware) only nudges: it breaks ties between
// equally matching chunks, never overrules a deciding rule.
const BOOST_DOMAIN_MATCH = 3.0;
// A contradictory generic allowance scores zero — it must not reach the model
// alongside the prohibition it contradicts.
const DEMOTE_CONTRADICTION = 0.1;

const { tokenize } = require("./tokenize");
const { detectDomain, SOFTWARE_TERMS, HARDWARE_TERMS } = require("./chunk");

const AI_TERMS = ["ai", "chatgpt", "copilot", "claude", "gpt", "llm"];
const FIRMWARE_TERMS = ["firmware", "embedded"];
const CAD_TERMS = ["cad", "pcb", "schematic", "circuit", "3d", "gerber", "step", "stl", "breadboard", "soldering"];
const RETURNED_TERMS = ["returned", "return", "resubmit", "resubmission"];
const REFERRAL_TERMS = ["referral", "referrals"];
const DISCLOSURE_TERMS = ["disclose", "disclosure"];
const CONSEQUENCE_TERMS = ["exceed", "hide", "hiding", "consequence", "fraud", "ban", "penalty"];
const HOURS_TERMS = ["hour", "hours", "deflate", "deflation", "reduce", "payout"];

// Precomputes term frequencies once per corpus build so scoring a question is
// just a walk over the postings rather than a re-tokenisation of every chunk.
function buildIndex(chunks) {
  const docs = chunks.map((chunk) => {
    const terms = tokenize(`${chunk.heading || ""} ${chunk.text}`);
    const freq = new Map();
    for (const term of terms) freq.set(term, (freq.get(term) || 0) + 1);
    return { chunk, freq, length: terms.length };
  });

  const docFreq = new Map();
  for (const doc of docs) {
    for (const term of doc.freq.keys()) docFreq.set(term, (docFreq.get(term) || 0) + 1);
  }

  const totalLength = docs.reduce((sum, d) => sum + d.length, 0);
  return { docs, docFreq, avgLength: docs.length > 0 ? totalLength / docs.length : 0 };
}

function classifyQuery(queryTerms) {
  const has = (list) => queryTerms.some((term) => list.includes(term));
  const hasSet = (set) => queryTerms.some((term) => set.has(term));
  const isFirmwareQuery = has(FIRMWARE_TERMS);
  return {
    isAiQuery: has(AI_TERMS),
    isFirmwareQuery,
    isSoftwareQuery: hasSet(SOFTWARE_TERMS),
    isHardwareQuery: !isFirmwareQuery && hasSet(HARDWARE_TERMS),
    isCadOrPcbQuery: has(CAD_TERMS),
    isReadmeQuery: queryTerms.some((term) => term === "readme"),
    isReturnedQuery: has(RETURNED_TERMS),
    isReferralQuery: has(REFERRAL_TERMS),
    isDisclosureQuery: has(DISCLOSURE_TERMS),
    isConsequenceQuery: has(CONSEQUENCE_TERMS),
    queryMentionsHours: has(HOURS_TERMS),
  };
}

function bm25TermScore(tf, docLength, avgLength, idf) {
  const norm = tf * (K1 + 1);
  const denom = tf + K1 * (1 - B + (B * docLength) / (avgLength || 1));
  return idf * (norm / denom);
}

function baseScore(doc, queryTerms, total, docFreq, avgLength) {
  let value = 0;
  for (const term of queryTerms) {
    const tf = doc.freq.get(term);
    if (!tf) continue;
    // +1 inside the log keeps the weight positive for a term that appears in
    // every chunk, rather than letting it push a score negative.
    const idf = Math.log(1 + (total - docFreq.get(term) + 0.5) / (docFreq.get(term) + 0.5));
    value += bm25TermScore(tf, doc.length, avgLength, idf);
  }
  return value;
}

function aiChunkSignals(text, heading, combined) {
  return {
    has30Percent: /30\s*%|30\s*percent|hard ceiling/i.test(combined),
    isHardwareAiProhibition:
      /(?:hardware|cad|pcb|3d|step)/i.test(text) &&
      /(?:not allowed|100%\s*original|0%\s*ai|not\s+(?:be\s+)?generated by ai|ai cannot generate|custom designs by you)/i.test(text),
    isFirmwareAiRule: /firmware/i.test(text) && /(?:30%|standard software code limit|microcontroller)/i.test(text),
    isReadmeAiRule: /readme/i.test(text) && /(?:cannot be built by ai|write your own readme)/i.test(text),
    isDisclosureChunk: /disclose|disclosure/i.test(text),
    isConsequenceChunk: /(?:exceed|hide|hiding|consequence|fraud|permanent ban|reject your project|penaliz)/i.test(text),
    isGenericAiAllowance:
      (/using ai tools|permitted|30% of (?:the total|your project's) code/i.test(combined)),
    isVagueHonestyHeading: /be honest about ai/i.test(heading),
    isVagueAllowance: /using ai tools/i.test(text),
  };
}

function applyAiBoost(value, flags, signals) {
  if (!flags.isAiQuery) return value;
  if (flags.isFirmwareQuery) {
    if (signals.isFirmwareAiRule) return value + BOOST_DECIDING_RULE;
    if (signals.isHardwareAiProhibition) return value * DEMOTE_CONTRADICTION;
    return value;
  }
  if (flags.isHardwareQuery || flags.isCadOrPcbQuery) {
    // Specific rule: Hardware CAD/PCB 0% AI strictly beats generic software AI allowance
    if (signals.isHardwareAiProhibition) return value + BOOST_DECIDING_RULE;
    const generic = signals.isGenericAiAllowance && !signals.isHardwareAiProhibition && !signals.isReadmeAiRule;
    if (generic) return 0;
    return value;
  }
  if (flags.isReadmeQuery) {
    if (signals.isReadmeAiRule) return value + BOOST_DECIDING_RULE;
    const generic = signals.isGenericAiAllowance && !signals.isHardwareAiProhibition && !signals.isReadmeAiRule;
    if (generic) return 0;
    return value;
  }
  if (flags.isDisclosureQuery) {
    if (signals.isDisclosureChunk) return value + BOOST_DECIDING_RULE;
    return value;
  }
  if (flags.isConsequenceQuery) {
    if (signals.isConsequenceChunk) return value + BOOST_DECIDING_RULE;
    return value;
  }
  // General AI query: prioritize specific 30% cap over vague mentions
  if (signals.has30Percent || signals.isHardwareAiProhibition) return value + BOOST_SPECIFIC_CAP;
  if (signals.isVagueHonestyHeading || (signals.isVagueAllowance && !signals.has30Percent)) {
    return value * DEMOTE_CONTRADICTION;
  }
  return value;
}

function chunkDomainSignals(domain, combined) {
  return {
    isHardwareChunk: domain === "hardware" ||
      /hardware-requirements|hardware\s+requirements|\bpcb\b|wiring\s+diagram|gerber|breadboard|soldering|\bcad\b|3d\s+model|\.step\b|\.stl\b/i.test(combined),
    isSoftwareChunk: domain === "software" ||
      /software-requirements|software\s+requirements|\bsoftware\b|web\s+app|website|mobile\s+app|browser\s+extension|\bcli\b/i.test(combined),
  };
}

function applyDomainBoost(value, flags, domainSignals) {
  if (flags.isSoftwareQuery && !flags.isHardwareQuery) {
    // Software-specific query: NEVER return pure hardware chunks (wiring diagrams, PCBs, CAD, etc.)
    if (domainSignals.isHardwareChunk && !domainSignals.isSoftwareChunk) return 0;
    if (domainSignals.isSoftwareChunk) return value + BOOST_DOMAIN_MATCH;
    return value;
  }
  if (flags.isHardwareQuery && !flags.isSoftwareQuery) {
    // Hardware-specific query: NEVER return pure software chunks
    if (domainSignals.isSoftwareChunk && !domainSignals.isHardwareChunk) return 0;
    if (domainSignals.isHardwareChunk) return value + BOOST_DOMAIN_MATCH;
  }
  return value;
}

function applyReturnedBoost(value, flags, combined) {
  if (!flags.isReturnedQuery) return value;
  const isReturnedChunk =
    /(?:returned|needs changes|resubmitted|resubmit)/i.test(combined) &&
    /(?:feedback|adjustments|changes|not a (?:penalty|punishment)|eligible)/i.test(combined);
  const isDeflationChunk =
    /(?:deflate|deflation|override hours|reduce|deduct|cut|hours spent)/i.test(combined) &&
    /(?:doubt|claimed hours|genuine effort|audit|indicators converge)/i.test(combined);
  if (isReturnedChunk) value += BOOST_RETURNED_RULE;
  if (isDeflationChunk && !flags.queryMentionsHours) return 0;
  return value;
}

function applyReferralBoost(value, flags, combined) {
  if (!flags.isReferralQuery) return value;
  const isReferralChunk = /referral/i.test(combined);
  const hasExpiration = /(?:48\s*hours?|2\s*days?|expire|expiration)/i.test(combined);
  if (isReferralChunk && hasExpiration) return value + BOOST_DECIDING_RULE;
  return value;
}

function boostedValue(base, doc, flags) {
  const text = doc.chunk.text || "";
  const heading = doc.chunk.heading || "";
  const source = doc.chunk.source || "";
  const domain = doc.chunk.domain || detectDomain(text);
  const combined = `${heading} ${text} ${source}`;
  const rawSignals = aiChunkSignals(text, heading, combined);
  // The generic-allowance exclusion needs the prohibition context resolved
  // first: a chunk that IS the prohibition is never "generic".
  const signals = {
    ...rawSignals,
    isGenericAiAllowance:
      rawSignals.isGenericAiAllowance && !rawSignals.isHardwareAiProhibition && !rawSignals.isReadmeAiRule,
  };
  let value = applyAiBoost(base, flags, signals);
  if (value === 0) return 0;
  value = applyDomainBoost(value, flags, chunkDomainSignals(domain, combined));
  if (value === 0) return 0;
  value = applyReturnedBoost(value, flags, combined);
  if (value === 0) return 0;
  value = applyReferralBoost(value, flags, combined);
  return value;
}

function score(index, queryTerms) {
  const { docs, docFreq, avgLength } = index;
  const total = docs.length;
  const flags = classifyQuery(queryTerms);
  return docs
    .map((doc) => {
      const base = baseScore(doc, queryTerms, total, docFreq, avgLength);
      if (base <= 0) return { chunk: doc.chunk, value: 0 };
      return { chunk: doc.chunk, value: boostedValue(base, doc, flags) };
    })
    .filter((r) => r.value > 0)
    .sort((a, b) => b.value - a.value);
}

module.exports = {
  K1,
  B,
  BOOST_DECIDING_RULE,
  BOOST_SPECIFIC_CAP,
  BOOST_RETURNED_RULE,
  BOOST_DOMAIN_MATCH,
  DEMOTE_CONTRADICTION,
  buildIndex,
  classifyQuery,
  bm25TermScore,
  baseScore,
  aiChunkSignals,
  applyAiBoost,
  chunkDomainSignals,
  applyDomainBoost,
  applyReturnedBoost,
  applyReferralBoost,
  boostedValue,
  score,
};
